// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: analytics/v1/analytics.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetLeaderboard_FullMethodName     = "/analytics.v1.AnalyticsService/GetLeaderboard"
	AnalyticsService_GetStudentStats_FullMethodName    = "/analytics.v1.AnalyticsService/GetStudentStats"
	AnalyticsService_GetMentorStats_FullMethodName     = "/analytics.v1.AnalyticsService/GetMentorStats"
	AnalyticsService_GetPlatformMetrics_FullMethodName = "/analytics.v1.AnalyticsService/GetPlatformMetrics"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
	GetStudentStats(ctx context.Context, in *GetStudentStatsRequest, opts ...grpc.CallOption) (*GetStudentStatsResponse, error)
	GetMentorStats(ctx context.Context, in *GetMentorStatsRequest, opts ...grpc.CallOption) (*GetMentorStatsResponse, error)
	GetPlatformMetrics(ctx context.Context, in *GetPlatformMetricsRequest, opts ...grpc.CallOption) (*GetPlatformMetricsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetStudentStats(ctx context.Context, in *GetStudentStatsRequest, opts ...grpc.CallOption) (*GetStudentStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetStudentStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMentorStats(ctx context.Context, in *GetMentorStatsRequest, opts ...grpc.CallOption) (*GetMentorStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMentorStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMentorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPlatformMetrics(ctx context.Context, in *GetPlatformMetricsRequest, opts ...grpc.CallOption) (*GetPlatformMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformMetricsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPlatformMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations should embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	GetStudentStats(context.Context, *GetStudentStatsRequest) (*GetStudentStatsResponse, error)
	GetMentorStats(context.Context, *GetMentorStatsRequest) (*GetMentorStatsResponse, error)
	GetPlatformMetrics(context.Context, *GetPlatformMetricsRequest) (*GetPlatformMetricsResponse, error)
}

// UnimplementedAnalyticsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetStudentStats(context.Context, *GetStudentStatsRequest) (*GetStudentStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMentorStats(context.Context, *GetMentorStatsRequest) (*GetMentorStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMentorStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPlatformMetrics(context.Context, *GetPlatformMetricsRequest) (*GetPlatformMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetStudentStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetStudentStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetStudentStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetStudentStats(ctx, req.(*GetStudentStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMentorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMentorStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMentorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMentorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMentorStats(ctx, req.(*GetMentorStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPlatformMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPlatformMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPlatformMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPlatformMetrics(ctx, req.(*GetPlatformMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeaderboard",
			Handler:    _AnalyticsService_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetStudentStats",
			Handler:    _AnalyticsService_GetStudentStats_Handler,
		},
		{
			MethodName: "GetMentorStats",
			Handler:    _AnalyticsService_GetMentorStats_Handler,
		},
		{
			MethodName: "GetPlatformMetrics",
			Handler:    _AnalyticsService_GetPlatformMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
