// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: analytics/v1/analytics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetLeaderboardRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetStudentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentStatsRequest) Reset() {
	*x = GetStudentStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentStatsRequest) ProtoMessage() {}

func (x *GetStudentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudentStatsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetStudentStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QuestionsAsked    int32                  `protobuf:"varint,1,opt,name=questions_asked,json=questionsAsked,proto3" json:"questions_asked,omitempty"`
	QuestionsAnswered int32                  `protobuf:"varint,2,opt,name=questions_answered,json=questionsAnswered,proto3" json:"questions_answered,omitempty"`
	ResolutionRate    float64                `protobuf:"fixed64,3,opt,name=resolution_rate,json=resolutionRate,proto3" json:"resolution_rate,omitempty"`
	Weaknesses        []*TopicWeakness       `protobuf:"bytes,4,rep,name=weaknesses,proto3" json:"weaknesses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStudentStatsResponse) Reset() {
	*x = GetStudentStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentStatsResponse) ProtoMessage() {}

func (x *GetStudentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStudentStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentStatsResponse) GetQuestionsAsked() int32 {
	if x != nil {
		return x.QuestionsAsked
	}
	return 0
}

func (x *GetStudentStatsResponse) GetQuestionsAnswered() int32 {
	if x != nil {
		return x.QuestionsAnswered
	}
	return 0
}

func (x *GetStudentStatsResponse) GetResolutionRate() float64 {
	if x != nil {
		return x.ResolutionRate
	}
	return 0
}

func (x *GetStudentStatsResponse) GetWeaknesses() []*TopicWeakness {
	if x != nil {
		return x.Weaknesses
	}
	return nil
}

type GetMentorStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentorId      string                 `protobuf:"bytes,1,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMentorStatsRequest) Reset() {
	*x = GetMentorStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMentorStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMentorStatsRequest) ProtoMessage() {}

func (x *GetMentorStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMentorStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMentorStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetMentorStatsRequest) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *GetMentorStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetMentorStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QuestionsAnswered int32                  `protobuf:"varint,1,opt,name=questions_answered,json=questionsAnswered,proto3" json:"questions_answered,omitempty"`
	AcceptedSolutions int32                  `protobuf:"varint,2,opt,name=accepted_solutions,json=acceptedSolutions,proto3" json:"accepted_solutions,omitempty"`
	TotalUpvotes      int32                  `protobuf:"varint,3,opt,name=total_upvotes,json=totalUpvotes,proto3" json:"total_upvotes,omitempty"`
	SkipRate          int32                  `protobuf:"varint,4,opt,name=skip_rate,json=skipRate,proto3" json:"skip_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMentorStatsResponse) Reset() {
	*x = GetMentorStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMentorStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMentorStatsResponse) ProtoMessage() {}

func (x *GetMentorStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMentorStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMentorStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMentorStatsResponse) GetQuestionsAnswered() int32 {
	if x != nil {
		return x.QuestionsAnswered
	}
	return 0
}

func (x *GetMentorStatsResponse) GetAcceptedSolutions() int32 {
	if x != nil {
		return x.AcceptedSolutions
	}
	return 0
}

func (x *GetMentorStatsResponse) GetTotalUpvotes() int32 {
	if x != nil {
		return x.TotalUpvotes
	}
	return 0
}

func (x *GetMentorStatsResponse) GetSkipRate() int32 {
	if x != nil {
		return x.SkipRate
	}
	return 0
}

type GetPlatformMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformMetricsRequest) Reset() {
	*x = GetPlatformMetricsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformMetricsRequest) ProtoMessage() {}

func (x *GetPlatformMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlatformMetricsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetPlatformMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActiveStudents       int32                  `protobuf:"varint,1,opt,name=active_students,json=activeStudents,proto3" json:"active_students,omitempty"`
	ActiveMentors        int32                  `protobuf:"varint,2,opt,name=active_mentors,json=activeMentors,proto3" json:"active_mentors,omitempty"`
	TotalQuestions       int32                  `protobuf:"varint,3,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	PendingQuestions     int32                  `protobuf:"varint,4,opt,name=pending_questions,json=pendingQuestions,proto3" json:"pending_questions,omitempty"`
	AvgResponseTimeHours float64                `protobuf:"fixed64,5,opt,name=avg_response_time_hours,json=avgResponseTimeHours,proto3" json:"avg_response_time_hours,omitempty"`
	ResolutionRate       float64                `protobuf:"fixed64,6,opt,name=resolution_rate,json=resolutionRate,proto3" json:"resolution_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPlatformMetricsResponse) Reset() {
	*x = GetPlatformMetricsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformMetricsResponse) ProtoMessage() {}

func (x *GetPlatformMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlatformMetricsResponse) GetActiveStudents() int32 {
	if x != nil {
		return x.ActiveStudents
	}
	return 0
}

func (x *GetPlatformMetricsResponse) GetActiveMentors() int32 {
	if x != nil {
		return x.ActiveMentors
	}
	return 0
}

func (x *GetPlatformMetricsResponse) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *GetPlatformMetricsResponse) GetPendingQuestions() int32 {
	if x != nil {
		return x.PendingQuestions
	}
	return 0
}

func (x *GetPlatformMetricsResponse) GetAvgResponseTimeHours() float64 {
	if x != nil {
		return x.AvgResponseTimeHours
	}
	return 0
}

func (x *GetPlatformMetricsResponse) GetResolutionRate() float64 {
	if x != nil {
		return x.ResolutionRate
	}
	return 0
}

type LeaderboardEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MentorId          string                 `protobuf:"bytes,1,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	MentorName        string                 `protobuf:"bytes,2,opt,name=mentor_name,json=mentorName,proto3" json:"mentor_name,omitempty"`
	Rank              int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	QuestionsAnswered int32                  `protobuf:"varint,4,opt,name=questions_answered,json=questionsAnswered,proto3" json:"questions_answered,omitempty"`
	Upvotes           int32                  `protobuf:"varint,5,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	StudentsHelped    int32                  `protobuf:"varint,6,opt,name=students_helped,json=studentsHelped,proto3" json:"students_helped,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderboardEntry) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *LeaderboardEntry) GetMentorName() string {
	if x != nil {
		return x.MentorName
	}
	return ""
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetQuestionsAnswered() int32 {
	if x != nil {
		return x.QuestionsAnswered
	}
	return 0
}

func (x *LeaderboardEntry) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *LeaderboardEntry) GetStudentsHelped() int32 {
	if x != nil {
		return x.StudentsHelped
	}
	return 0
}

type TopicWeakness struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Subject        string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic          string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	QuestionCount  int32                  `protobuf:"varint,3,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	ResolutionRate float64                `protobuf:"fixed64,4,opt,name=resolution_rate,json=resolutionRate,proto3" json:"resolution_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopicWeakness) Reset() {
	*x = TopicWeakness{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicWeakness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicWeakness) ProtoMessage() {}

func (x *TopicWeakness) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicWeakness.ProtoReflect.Descriptor instead.
func (*TopicWeakness) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *TopicWeakness) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TopicWeakness) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicWeakness) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *TopicWeakness) GetResolutionRate() float64 {
	if x != nil {
		return x.ResolutionRate
	}
	return 0
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\"E\n" +
	"\x15GetLeaderboardRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"R\n" +
	"\x16GetLeaderboardResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.analytics.v1.LeaderboardEntryR\aentries\"O\n" +
	"\x16GetStudentStatsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\xd7\x01\n" +
	"\x17GetStudentStatsResponse\x12'\n" +
	"\x0fquestions_asked\x18\x01 \x01(\x05R\x0equestionsAsked\x12-\n" +
	"\x12questions_answered\x18\x02 \x01(\x05R\x11questionsAnswered\x12'\n" +
	"\x0fresolution_rate\x18\x03 \x01(\x01R\x0eresolutionRate\x12;\n" +
	"\n" +
	"weaknesses\x18\x04 \x03(\v2\x1b.analytics.v1.TopicWeaknessR\n" +
	"weaknesses\"L\n" +
	"\x15GetMentorStatsRequest\x12\x1b\n" +
	"\tmentor_id\x18\x01 \x01(\tR\bmentorId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\xb8\x01\n" +
	"\x16GetMentorStatsResponse\x12-\n" +
	"\x12questions_answered\x18\x01 \x01(\x05R\x11questionsAnswered\x12-\n" +
	"\x12accepted_solutions\x18\x02 \x01(\x05R\x11acceptedSolutions\x12#\n" +
	"\rtotal_upvotes\x18\x03 \x01(\x05R\ftotalUpvotes\x12\x1b\n" +
	"\tskip_rate\x18\x04 \x01(\x05R\bskipRate\"3\n" +
	"\x19GetPlatformMetricsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"\xa2\x02\n" +
	"\x1aGetPlatformMetricsResponse\x12'\n" +
	"\x0factive_students\x18\x01 \x01(\x05R\x0eactiveStudents\x12%\n" +
	"\x0eactive_mentors\x18\x02 \x01(\x05R\ractiveMentors\x12'\n" +
	"\x0ftotal_questions\x18\x03 \x01(\x05R\x0etotalQuestions\x12+\n" +
	"\x11pending_questions\x18\x04 \x01(\x05R\x10pendingQuestions\x125\n" +
	"\x17avg_response_time_hours\x18\x05 \x01(\x01R\x14avgResponseTimeHours\x12'\n" +
	"\x0fresolution_rate\x18\x06 \x01(\x01R\x0eresolutionRate\"\xd6\x01\n" +
	"\x10LeaderboardEntry\x12\x1b\n" +
	"\tmentor_id\x18\x01 \x01(\tR\bmentorId\x12\x1f\n" +
	"\vmentor_name\x18\x02 \x01(\tR\n" +
	"mentorName\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12-\n" +
	"\x12questions_answered\x18\x04 \x01(\x05R\x11questionsAnswered\x12\x18\n" +
	"\aupvotes\x18\x05 \x01(\x05R\aupvotes\x12'\n" +
	"\x0fstudents_helped\x18\x06 \x01(\x05R\x0estudentsHelped\"\x8f\x01\n" +
	"\rTopicWeakness\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12%\n" +
	"\x0equestion_count\x18\x03 \x01(\x05R\rquestionCount\x12'\n" +
	"\x0fresolution_rate\x18\x04 \x01(\x01R\x0eresolutionRate2\x95\x03\n" +
	"\x10AnalyticsService\x12[\n" +
	"\x0eGetLeaderboard\x12#.analytics.v1.GetLeaderboardRequest\x1a$.analytics.v1.GetLeaderboardResponse\x12^\n" +
	"\x0fGetStudentStats\x12$.analytics.v1.GetStudentStatsRequest\x1a%.analytics.v1.GetStudentStatsResponse\x12[\n" +
	"\x0eGetMentorStats\x12#.analytics.v1.GetMentorStatsRequest\x1a$.analytics.v1.GetMentorStatsResponse\x12g\n" +
	"\x12GetPlatformMetrics\x12'.analytics.v1.GetPlatformMetricsRequest\x1a(.analytics.v1.GetPlatformMetricsResponseB\"Z preppi.com/proto/analytics/v1;v1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*GetLeaderboardRequest)(nil),      // 0: analytics.v1.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),     // 1: analytics.v1.GetLeaderboardResponse
	(*GetStudentStatsRequest)(nil),     // 2: analytics.v1.GetStudentStatsRequest
	(*GetStudentStatsResponse)(nil),    // 3: analytics.v1.GetStudentStatsResponse
	(*GetMentorStatsRequest)(nil),      // 4: analytics.v1.GetMentorStatsRequest
	(*GetMentorStatsResponse)(nil),     // 5: analytics.v1.GetMentorStatsResponse
	(*GetPlatformMetricsRequest)(nil),  // 6: analytics.v1.GetPlatformMetricsRequest
	(*GetPlatformMetricsResponse)(nil), // 7: analytics.v1.GetPlatformMetricsResponse
	(*LeaderboardEntry)(nil),           // 8: analytics.v1.LeaderboardEntry
	(*TopicWeakness)(nil),              // 9: analytics.v1.TopicWeakness
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	8, // 0: analytics.v1.GetLeaderboardResponse.entries:type_name -> analytics.v1.LeaderboardEntry
	9, // 1: analytics.v1.GetStudentStatsResponse.weaknesses:type_name -> analytics.v1.TopicWeakness
	0, // 2: analytics.v1.AnalyticsService.GetLeaderboard:input_type -> analytics.v1.GetLeaderboardRequest
	2, // 3: analytics.v1.AnalyticsService.GetStudentStats:input_type -> analytics.v1.GetStudentStatsRequest
	4, // 4: analytics.v1.AnalyticsService.GetMentorStats:input_type -> analytics.v1.GetMentorStatsRequest
	6, // 5: analytics.v1.AnalyticsService.GetPlatformMetrics:input_type -> analytics.v1.GetPlatformMetricsRequest
	1, // 6: analytics.v1.AnalyticsService.GetLeaderboard:output_type -> analytics.v1.GetLeaderboardResponse
	3, // 7: analytics.v1.AnalyticsService.GetStudentStats:output_type -> analytics.v1.GetStudentStatsResponse
	5, // 8: analytics.v1.AnalyticsService.GetMentorStats:output_type -> analytics.v1.GetMentorStatsResponse
	7, // 9: analytics.v1.AnalyticsService.GetPlatformMetrics:output_type -> analytics.v1.GetPlatformMetricsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
