// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: admin/v1/admin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportStatus int32

const (
	ReportStatus_REPORT_STATUS_UNSPECIFIED ReportStatus = 0
	ReportStatus_REPORT_STATUS_PENDING     ReportStatus = 1
	ReportStatus_REPORT_STATUS_REVIEWED    ReportStatus = 2
	ReportStatus_REPORT_STATUS_ACTIONED    ReportStatus = 3
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "REPORT_STATUS_UNSPECIFIED",
		1: "REPORT_STATUS_PENDING",
		2: "REPORT_STATUS_REVIEWED",
		3: "REPORT_STATUS_ACTIONED",
	}
	ReportStatus_value = map[string]int32{
		"REPORT_STATUS_UNSPECIFIED": 0,
		"REPORT_STATUS_PENDING":     1,
		"REPORT_STATUS_REVIEWED":    2,
		"REPORT_STATUS_ACTIONED":    3,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_admin_v1_admin_proto_enumTypes[0]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type ReportType int32

const (
	ReportType_REPORT_TYPE_UNSPECIFIED           ReportType = 0
	ReportType_REPORT_TYPE_ABUSE                 ReportType = 1
	ReportType_REPORT_TYPE_SPAM                  ReportType = 2
	ReportType_REPORT_TYPE_INAPPROPRIATE_CONTENT ReportType = 3
	ReportType_REPORT_TYPE_OTHER                 ReportType = 4
)

// Enum value maps for ReportType.
var (
	ReportType_name = map[int32]string{
		0: "REPORT_TYPE_UNSPECIFIED",
		1: "REPORT_TYPE_ABUSE",
		2: "REPORT_TYPE_SPAM",
		3: "REPORT_TYPE_INAPPROPRIATE_CONTENT",
		4: "REPORT_TYPE_OTHER",
	}
	ReportType_value = map[string]int32{
		"REPORT_TYPE_UNSPECIFIED":           0,
		"REPORT_TYPE_ABUSE":                 1,
		"REPORT_TYPE_SPAM":                  2,
		"REPORT_TYPE_INAPPROPRIATE_CONTENT": 3,
		"REPORT_TYPE_OTHER":                 4,
	}
)

func (x ReportType) Enum() *ReportType {
	p := new(ReportType)
	*p = x
	return p
}

func (x ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_admin_proto_enumTypes[1].Descriptor()
}

func (ReportType) Type() protoreflect.EnumType {
	return &file_admin_v1_admin_proto_enumTypes[1]
}

func (x ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportType.Descriptor instead.
func (ReportType) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReporterId    string                 `protobuf:"bytes,1,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Type          ReportType             `protobuf:"varint,2,opt,name=type,proto3,enum=admin.v1.ReportType" json:"type,omitempty"`
	ContentId     string                 `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *CreateReportRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_REPORT_TYPE_UNSPECIFIED
}

func (x *CreateReportRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *CreateReportRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Status        ReportStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=admin.v1.ReportStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *CreateReportResponse) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReportStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=admin.v1.ReportStatus" json:"status,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListReportsRequest) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *ListReportsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListReportsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ReviewReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ActionTaken   bool                   `protobuf:"varint,2,opt,name=action_taken,json=actionTaken,proto3" json:"action_taken,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewReportRequest) Reset() {
	*x = ReviewReportRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewReportRequest) ProtoMessage() {}

func (x *ReviewReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewReportRequest.ProtoReflect.Descriptor instead.
func (*ReviewReportRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReviewReportRequest) GetActionTaken() bool {
	if x != nil {
		return x.ActionTaken
	}
	return false
}

func (x *ReviewReportRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ReviewReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReportStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=admin.v1.ReportStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewReportResponse) Reset() {
	*x = ReviewReportResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewReportResponse) ProtoMessage() {}

func (x *ReviewReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewReportResponse.ProtoReflect.Descriptor instead.
func (*ReviewReportResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewReportResponse) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

type GetPendingMentorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     string                 `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingMentorsRequest) Reset() {
	*x = GetPendingMentorsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingMentorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingMentorsRequest) ProtoMessage() {}

func (x *GetPendingMentorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingMentorsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingMentorsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetPendingMentorsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetPendingMentorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPendingMentorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mentors       []*PendingMentor       `protobuf:"bytes,1,rep,name=mentors,proto3" json:"mentors,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingMentorsResponse) Reset() {
	*x = GetPendingMentorsResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingMentorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingMentorsResponse) ProtoMessage() {}

func (x *GetPendingMentorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingMentorsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingMentorsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingMentorsResponse) GetMentors() []*PendingMentor {
	if x != nil {
		return x.Mentors
	}
	return nil
}

func (x *GetPendingMentorsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

type GetDashboardResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers             int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveMentors          int32                  `protobuf:"varint,2,opt,name=active_mentors,json=activeMentors,proto3" json:"active_mentors,omitempty"`
	ActiveStudents         int32                  `protobuf:"varint,3,opt,name=active_students,json=activeStudents,proto3" json:"active_students,omitempty"`
	PendingQuestions       int32                  `protobuf:"varint,4,opt,name=pending_questions,json=pendingQuestions,proto3" json:"pending_questions,omitempty"`
	PendingReports         int32                  `protobuf:"varint,5,opt,name=pending_reports,json=pendingReports,proto3" json:"pending_reports,omitempty"`
	PendingMentorApprovals int32                  `protobuf:"varint,6,opt,name=pending_mentor_approvals,json=pendingMentorApprovals,proto3" json:"pending_mentor_approvals,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *GetDashboardResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetActiveMentors() int32 {
	if x != nil {
		return x.ActiveMentors
	}
	return 0
}

func (x *GetDashboardResponse) GetActiveStudents() int32 {
	if x != nil {
		return x.ActiveStudents
	}
	return 0
}

func (x *GetDashboardResponse) GetPendingQuestions() int32 {
	if x != nil {
		return x.PendingQuestions
	}
	return 0
}

func (x *GetDashboardResponse) GetPendingReports() int32 {
	if x != nil {
		return x.PendingReports
	}
	return 0
}

func (x *GetDashboardResponse) GetPendingMentorApprovals() int32 {
	if x != nil {
		return x.PendingMentorApprovals
	}
	return 0
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReporterId    string                 `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Type          ReportType             `protobuf:"varint,3,opt,name=type,proto3,enum=admin.v1.ReportType" json:"type,omitempty"`
	ContentId     string                 `protobuf:"bytes,4,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        ReportStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=admin.v1.ReportStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *Report) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_REPORT_TYPE_UNSPECIFIED
}

func (x *Report) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *Report) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Report) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *Report) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PendingMentor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Expertise     []string               `protobuf:"bytes,4,rep,name=expertise,proto3" json:"expertise,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingMentor) Reset() {
	*x = PendingMentor{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingMentor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMentor) ProtoMessage() {}

func (x *PendingMentor) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMentor.ProtoReflect.Descriptor instead.
func (*PendingMentor) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *PendingMentor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PendingMentor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PendingMentor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PendingMentor) GetExpertise() []string {
	if x != nil {
		return x.Expertise
	}
	return nil
}

func (x *PendingMentor) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *PendingMentor) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\badmin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\x13CreateReportRequest\x12\x1f\n" +
	"\vreporter_id\x18\x01 \x01(\tR\n" +
	"reporterId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.admin.v1.ReportTypeR\x04type\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"c\n" +
	"\x14CreateReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.admin.v1.ReportStatusR\x06status\"\x80\x01\n" +
	"\x12ListReportsRequest\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.admin.v1.ReportStatusR\x06status\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"i\n" +
	"\x13ListReportsResponse\x12*\n" +
	"\areports\x18\x01 \x03(\v2\x10.admin.v1.ReportR\areports\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"m\n" +
	"\x13ReviewReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12!\n" +
	"\faction_taken\x18\x02 \x01(\bR\vactionTaken\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"F\n" +
	"\x14ReviewReportResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.admin.v1.ReportStatusR\x06status\"V\n" +
	"\x18GetPendingMentorsRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"v\n" +
	"\x19GetPendingMentorsResponse\x121\n" +
	"\amentors\x18\x01 \x03(\v2\x17.admin.v1.PendingMentorR\amentors\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x15\n" +
	"\x13GetDashboardRequest\"\x97\x02\n" +
	"\x14GetDashboardResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12%\n" +
	"\x0eactive_mentors\x18\x02 \x01(\x05R\ractiveMentors\x12'\n" +
	"\x0factive_students\x18\x03 \x01(\x05R\x0eactiveStudents\x12+\n" +
	"\x11pending_questions\x18\x04 \x01(\x05R\x10pendingQuestions\x12'\n" +
	"\x0fpending_reports\x18\x05 \x01(\x05R\x0ependingReports\x128\n" +
	"\x18pending_mentor_approvals\x18\x06 \x01(\x05R\x16pendingMentorApprovals\"\x85\x02\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\tR\n" +
	"reporterId\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.admin.v1.ReportTypeR\x04type\x12\x1d\n" +
	"\n" +
	"content_id\x18\x04 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.admin.v1.ReportStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc3\x01\n" +
	"\rPendingMentor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\texpertise\x18\x04 \x03(\tR\texpertise\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12?\n" +
	"\rregistered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt*\x80\x01\n" +
	"\fReportStatus\x12\x1d\n" +
	"\x19REPORT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REPORT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16REPORT_STATUS_REVIEWED\x10\x02\x12\x1a\n" +
	"\x16REPORT_STATUS_ACTIONED\x10\x03*\x94\x01\n" +
	"\n" +
	"ReportType\x12\x1b\n" +
	"\x17REPORT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11REPORT_TYPE_ABUSE\x10\x01\x12\x14\n" +
	"\x10REPORT_TYPE_SPAM\x10\x02\x12%\n" +
	"!REPORT_TYPE_INAPPROPRIATE_CONTENT\x10\x03\x12\x15\n" +
	"\x11REPORT_TYPE_OTHER\x10\x042\xa5\x03\n" +
	"\fAdminService\x12M\n" +
	"\fCreateReport\x12\x1d.admin.v1.CreateReportRequest\x1a\x1e.admin.v1.CreateReportResponse\x12J\n" +
	"\vListReports\x12\x1c.admin.v1.ListReportsRequest\x1a\x1d.admin.v1.ListReportsResponse\x12M\n" +
	"\fReviewReport\x12\x1d.admin.v1.ReviewReportRequest\x1a\x1e.admin.v1.ReviewReportResponse\x12\\\n" +
	"\x11GetPendingMentors\x12\".admin.v1.GetPendingMentorsRequest\x1a#.admin.v1.GetPendingMentorsResponse\x12M\n" +
	"\fGetDashboard\x12\x1d.admin.v1.GetDashboardRequest\x1a\x1e.admin.v1.GetDashboardResponseB\x1eZ\x1cpreppi.com/proto/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_admin_v1_admin_proto_goTypes = []any{
	(ReportStatus)(0),                 // 0: admin.v1.ReportStatus
	(ReportType)(0),                   // 1: admin.v1.ReportType
	(*CreateReportRequest)(nil),       // 2: admin.v1.CreateReportRequest
	(*CreateReportResponse)(nil),      // 3: admin.v1.CreateReportResponse
	(*ListReportsRequest)(nil),        // 4: admin.v1.ListReportsRequest
	(*ListReportsResponse)(nil),       // 5: admin.v1.ListReportsResponse
	(*ReviewReportRequest)(nil),       // 6: admin.v1.ReviewReportRequest
	(*ReviewReportResponse)(nil),      // 7: admin.v1.ReviewReportResponse
	(*GetPendingMentorsRequest)(nil),  // 8: admin.v1.GetPendingMentorsRequest
	(*GetPendingMentorsResponse)(nil), // 9: admin.v1.GetPendingMentorsResponse
	(*GetDashboardRequest)(nil),       // 10: admin.v1.GetDashboardRequest
	(*GetDashboardResponse)(nil),      // 11: admin.v1.GetDashboardResponse
	(*Report)(nil),                    // 12: admin.v1.Report
	(*PendingMentor)(nil),             // 13: admin.v1.PendingMentor
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	1,  // 0: admin.v1.CreateReportRequest.type:type_name -> admin.v1.ReportType
	0,  // 1: admin.v1.CreateReportResponse.status:type_name -> admin.v1.ReportStatus
	0,  // 2: admin.v1.ListReportsRequest.status:type_name -> admin.v1.ReportStatus
	12, // 3: admin.v1.ListReportsResponse.reports:type_name -> admin.v1.Report
	0,  // 4: admin.v1.ReviewReportResponse.status:type_name -> admin.v1.ReportStatus
	13, // 5: admin.v1.GetPendingMentorsResponse.mentors:type_name -> admin.v1.PendingMentor
	1,  // 6: admin.v1.Report.type:type_name -> admin.v1.ReportType
	0,  // 7: admin.v1.Report.status:type_name -> admin.v1.ReportStatus
	14, // 8: admin.v1.Report.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: admin.v1.PendingMentor.registered_at:type_name -> google.protobuf.Timestamp
	2,  // 10: admin.v1.AdminService.CreateReport:input_type -> admin.v1.CreateReportRequest
	4,  // 11: admin.v1.AdminService.ListReports:input_type -> admin.v1.ListReportsRequest
	6,  // 12: admin.v1.AdminService.ReviewReport:input_type -> admin.v1.ReviewReportRequest
	8,  // 13: admin.v1.AdminService.GetPendingMentors:input_type -> admin.v1.GetPendingMentorsRequest
	10, // 14: admin.v1.AdminService.GetDashboard:input_type -> admin.v1.GetDashboardRequest
	3,  // 15: admin.v1.AdminService.CreateReport:output_type -> admin.v1.CreateReportResponse
	5,  // 16: admin.v1.AdminService.ListReports:output_type -> admin.v1.ListReportsResponse
	7,  // 17: admin.v1.AdminService.ReviewReport:output_type -> admin.v1.ReviewReportResponse
	9,  // 18: admin.v1.AdminService.GetPendingMentors:output_type -> admin.v1.GetPendingMentorsResponse
	11, // 19: admin.v1.AdminService.GetDashboard:output_type -> admin.v1.GetDashboardResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
