// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: solution/v1/solution.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolutionService_CreateSolution_FullMethodName          = "/solution.v1.SolutionService/CreateSolution"
	SolutionService_GetSolutionById_FullMethodName         = "/solution.v1.SolutionService/GetSolutionById"
	SolutionService_ListSolutionsByQuestion_FullMethodName = "/solution.v1.SolutionService/ListSolutionsByQuestion"
	SolutionService_VoteSolution_FullMethodName            = "/solution.v1.SolutionService/VoteSolution"
	SolutionService_AcceptSolution_FullMethodName          = "/solution.v1.SolutionService/AcceptSolution"
	SolutionService_CreateFollowUp_FullMethodName          = "/solution.v1.SolutionService/CreateFollowUp"
	SolutionService_ListFollowUps_FullMethodName           = "/solution.v1.SolutionService/ListFollowUps"
)

// SolutionServiceClient is the client API for SolutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolutionServiceClient interface {
	CreateSolution(ctx context.Context, in *CreateSolutionRequest, opts ...grpc.CallOption) (*CreateSolutionResponse, error)
	GetSolutionById(ctx context.Context, in *GetSolutionByIdRequest, opts ...grpc.CallOption) (*GetSolutionByIdResponse, error)
	ListSolutionsByQuestion(ctx context.Context, in *ListSolutionsByQuestionRequest, opts ...grpc.CallOption) (*ListSolutionsByQuestionResponse, error)
	VoteSolution(ctx context.Context, in *VoteSolutionRequest, opts ...grpc.CallOption) (*VoteSolutionResponse, error)
	AcceptSolution(ctx context.Context, in *AcceptSolutionRequest, opts ...grpc.CallOption) (*AcceptSolutionResponse, error)
	CreateFollowUp(ctx context.Context, in *CreateFollowUpRequest, opts ...grpc.CallOption) (*CreateFollowUpResponse, error)
	ListFollowUps(ctx context.Context, in *ListFollowUpsRequest, opts ...grpc.CallOption) (*ListFollowUpsResponse, error)
}

type solutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolutionServiceClient(cc grpc.ClientConnInterface) SolutionServiceClient {
	return &solutionServiceClient{cc}
}

func (c *solutionServiceClient) CreateSolution(ctx context.Context, in *CreateSolutionRequest, opts ...grpc.CallOption) (*CreateSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSolutionResponse)
	err := c.cc.Invoke(ctx, SolutionService_CreateSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) GetSolutionById(ctx context.Context, in *GetSolutionByIdRequest, opts ...grpc.CallOption) (*GetSolutionByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSolutionByIdResponse)
	err := c.cc.Invoke(ctx, SolutionService_GetSolutionById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) ListSolutionsByQuestion(ctx context.Context, in *ListSolutionsByQuestionRequest, opts ...grpc.CallOption) (*ListSolutionsByQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSolutionsByQuestionResponse)
	err := c.cc.Invoke(ctx, SolutionService_ListSolutionsByQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) VoteSolution(ctx context.Context, in *VoteSolutionRequest, opts ...grpc.CallOption) (*VoteSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteSolutionResponse)
	err := c.cc.Invoke(ctx, SolutionService_VoteSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) AcceptSolution(ctx context.Context, in *AcceptSolutionRequest, opts ...grpc.CallOption) (*AcceptSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptSolutionResponse)
	err := c.cc.Invoke(ctx, SolutionService_AcceptSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) CreateFollowUp(ctx context.Context, in *CreateFollowUpRequest, opts ...grpc.CallOption) (*CreateFollowUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFollowUpResponse)
	err := c.cc.Invoke(ctx, SolutionService_CreateFollowUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) ListFollowUps(ctx context.Context, in *ListFollowUpsRequest, opts ...grpc.CallOption) (*ListFollowUpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowUpsResponse)
	err := c.cc.Invoke(ctx, SolutionService_ListFollowUps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolutionServiceServer is the server API for SolutionService service.
// All implementations should embed UnimplementedSolutionServiceServer
// for forward compatibility.
type SolutionServiceServer interface {
	CreateSolution(context.Context, *CreateSolutionRequest) (*CreateSolutionResponse, error)
	GetSolutionById(context.Context, *GetSolutionByIdRequest) (*GetSolutionByIdResponse, error)
	ListSolutionsByQuestion(context.Context, *ListSolutionsByQuestionRequest) (*ListSolutionsByQuestionResponse, error)
	VoteSolution(context.Context, *VoteSolutionRequest) (*VoteSolutionResponse, error)
	AcceptSolution(context.Context, *AcceptSolutionRequest) (*AcceptSolutionResponse, error)
	CreateFollowUp(context.Context, *CreateFollowUpRequest) (*CreateFollowUpResponse, error)
	ListFollowUps(context.Context, *ListFollowUpsRequest) (*ListFollowUpsResponse, error)
}

// UnimplementedSolutionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolutionServiceServer struct{}

func (UnimplementedSolutionServiceServer) CreateSolution(context.Context, *CreateSolutionRequest) (*CreateSolutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSolution not implemented")
}
func (UnimplementedSolutionServiceServer) GetSolutionById(context.Context, *GetSolutionByIdRequest) (*GetSolutionByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSolutionById not implemented")
}
func (UnimplementedSolutionServiceServer) ListSolutionsByQuestion(context.Context, *ListSolutionsByQuestionRequest) (*ListSolutionsByQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSolutionsByQuestion not implemented")
}
func (UnimplementedSolutionServiceServer) VoteSolution(context.Context, *VoteSolutionRequest) (*VoteSolutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoteSolution not implemented")
}
func (UnimplementedSolutionServiceServer) AcceptSolution(context.Context, *AcceptSolutionRequest) (*AcceptSolutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptSolution not implemented")
}
func (UnimplementedSolutionServiceServer) CreateFollowUp(context.Context, *CreateFollowUpRequest) (*CreateFollowUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFollowUp not implemented")
}
func (UnimplementedSolutionServiceServer) ListFollowUps(context.Context, *ListFollowUpsRequest) (*ListFollowUpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowUps not implemented")
}
func (UnimplementedSolutionServiceServer) testEmbeddedByValue() {}

// UnsafeSolutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolutionServiceServer will
// result in compilation errors.
type UnsafeSolutionServiceServer interface {
	mustEmbedUnimplementedSolutionServiceServer()
}

func RegisterSolutionServiceServer(s grpc.ServiceRegistrar, srv SolutionServiceServer) {
	// If the following call panics, it indicates UnimplementedSolutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolutionService_ServiceDesc, srv)
}

func _SolutionService_CreateSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).CreateSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_CreateSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).CreateSolution(ctx, req.(*CreateSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_GetSolutionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSolutionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).GetSolutionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_GetSolutionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).GetSolutionById(ctx, req.(*GetSolutionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_ListSolutionsByQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSolutionsByQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).ListSolutionsByQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_ListSolutionsByQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).ListSolutionsByQuestion(ctx, req.(*ListSolutionsByQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_VoteSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).VoteSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_VoteSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).VoteSolution(ctx, req.(*VoteSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_AcceptSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).AcceptSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_AcceptSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).AcceptSolution(ctx, req.(*AcceptSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_CreateFollowUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFollowUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).CreateFollowUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_CreateFollowUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).CreateFollowUp(ctx, req.(*CreateFollowUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_ListFollowUps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowUpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).ListFollowUps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolutionService_ListFollowUps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).ListFollowUps(ctx, req.(*ListFollowUpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolutionService_ServiceDesc is the grpc.ServiceDesc for SolutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solution.v1.SolutionService",
	HandlerType: (*SolutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSolution",
			Handler:    _SolutionService_CreateSolution_Handler,
		},
		{
			MethodName: "GetSolutionById",
			Handler:    _SolutionService_GetSolutionById_Handler,
		},
		{
			MethodName: "ListSolutionsByQuestion",
			Handler:    _SolutionService_ListSolutionsByQuestion_Handler,
		},
		{
			MethodName: "VoteSolution",
			Handler:    _SolutionService_VoteSolution_Handler,
		},
		{
			MethodName: "AcceptSolution",
			Handler:    _SolutionService_AcceptSolution_Handler,
		},
		{
			MethodName: "CreateFollowUp",
			Handler:    _SolutionService_CreateFollowUp_Handler,
		},
		{
			MethodName: "ListFollowUps",
			Handler:    _SolutionService_ListFollowUps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solution/v1/solution.proto",
}
