// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: solution/v1/solution.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteType int32

const (
	VoteType_VOTE_TYPE_UNSPECIFIED VoteType = 0
	VoteType_VOTE_TYPE_UP          VoteType = 1
	VoteType_VOTE_TYPE_DOWN        VoteType = 2
)

// Enum value maps for VoteType.
var (
	VoteType_name = map[int32]string{
		0: "VOTE_TYPE_UNSPECIFIED",
		1: "VOTE_TYPE_UP",
		2: "VOTE_TYPE_DOWN",
	}
	VoteType_value = map[string]int32{
		"VOTE_TYPE_UNSPECIFIED": 0,
		"VOTE_TYPE_UP":          1,
		"VOTE_TYPE_DOWN":        2,
	}
)

func (x VoteType) Enum() *VoteType {
	p := new(VoteType)
	*p = x
	return p
}

func (x VoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_solution_v1_solution_proto_enumTypes[0].Descriptor()
}

func (VoteType) Type() protoreflect.EnumType {
	return &file_solution_v1_solution_proto_enumTypes[0]
}

func (x VoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteType.Descriptor instead.
func (VoteType) EnumDescriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{0}
}

type CreateSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	MentorId      string                 `protobuf:"bytes,2,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,4,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSolutionRequest) Reset() {
	*x = CreateSolutionRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSolutionRequest) ProtoMessage() {}

func (x *CreateSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSolutionRequest.ProtoReflect.Descriptor instead.
func (*CreateSolutionRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSolutionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *CreateSolutionRequest) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *CreateSolutionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSolutionRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type CreateSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *Solution              `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSolutionResponse) Reset() {
	*x = CreateSolutionResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSolutionResponse) ProtoMessage() {}

func (x *CreateSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSolutionResponse.ProtoReflect.Descriptor instead.
func (*CreateSolutionResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSolutionResponse) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type GetSolutionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SolutionId    string                 `protobuf:"bytes,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolutionByIdRequest) Reset() {
	*x = GetSolutionByIdRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolutionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolutionByIdRequest) ProtoMessage() {}

func (x *GetSolutionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolutionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetSolutionByIdRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{2}
}

func (x *GetSolutionByIdRequest) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

type GetSolutionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *Solution              `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolutionByIdResponse) Reset() {
	*x = GetSolutionByIdResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolutionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolutionByIdResponse) ProtoMessage() {}

func (x *GetSolutionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolutionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetSolutionByIdResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{3}
}

func (x *GetSolutionByIdResponse) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type ListSolutionsByQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSolutionsByQuestionRequest) Reset() {
	*x = ListSolutionsByQuestionRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSolutionsByQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSolutionsByQuestionRequest) ProtoMessage() {}

func (x *ListSolutionsByQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSolutionsByQuestionRequest.ProtoReflect.Descriptor instead.
func (*ListSolutionsByQuestionRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{4}
}

func (x *ListSolutionsByQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *ListSolutionsByQuestionRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSolutionsByQuestionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSolutionsByQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solutions     []*Solution            `protobuf:"bytes,1,rep,name=solutions,proto3" json:"solutions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSolutionsByQuestionResponse) Reset() {
	*x = ListSolutionsByQuestionResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSolutionsByQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSolutionsByQuestionResponse) ProtoMessage() {}

func (x *ListSolutionsByQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSolutionsByQuestionResponse.ProtoReflect.Descriptor instead.
func (*ListSolutionsByQuestionResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{5}
}

func (x *ListSolutionsByQuestionResponse) GetSolutions() []*Solution {
	if x != nil {
		return x.Solutions
	}
	return nil
}

func (x *ListSolutionsByQuestionResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type VoteSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SolutionId    string                 `protobuf:"bytes,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Vote          VoteType               `protobuf:"varint,3,opt,name=vote,proto3,enum=solution.v1.VoteType" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteSolutionRequest) Reset() {
	*x = VoteSolutionRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteSolutionRequest) ProtoMessage() {}

func (x *VoteSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteSolutionRequest.ProtoReflect.Descriptor instead.
func (*VoteSolutionRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{6}
}

func (x *VoteSolutionRequest) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *VoteSolutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VoteSolutionRequest) GetVote() VoteType {
	if x != nil {
		return x.Vote
	}
	return VoteType_VOTE_TYPE_UNSPECIFIED
}

type VoteSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upvotes       int32                  `protobuf:"varint,1,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	Downvotes     int32                  `protobuf:"varint,2,opt,name=downvotes,proto3" json:"downvotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteSolutionResponse) Reset() {
	*x = VoteSolutionResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteSolutionResponse) ProtoMessage() {}

func (x *VoteSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteSolutionResponse.ProtoReflect.Descriptor instead.
func (*VoteSolutionResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{7}
}

func (x *VoteSolutionResponse) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *VoteSolutionResponse) GetDownvotes() int32 {
	if x != nil {
		return x.Downvotes
	}
	return 0
}

type AcceptSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SolutionId    string                 `protobuf:"bytes,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptSolutionRequest) Reset() {
	*x = AcceptSolutionRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptSolutionRequest) ProtoMessage() {}

func (x *AcceptSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptSolutionRequest.ProtoReflect.Descriptor instead.
func (*AcceptSolutionRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptSolutionRequest) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *AcceptSolutionRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type AcceptSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptSolutionResponse) Reset() {
	*x = AcceptSolutionResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptSolutionResponse) ProtoMessage() {}

func (x *AcceptSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptSolutionResponse.ProtoReflect.Descriptor instead.
func (*AcceptSolutionResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptSolutionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type CreateFollowUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SolutionId    string                 `protobuf:"bytes,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,4,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFollowUpRequest) Reset() {
	*x = CreateFollowUpRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowUpRequest) ProtoMessage() {}

func (x *CreateFollowUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowUpRequest.ProtoReflect.Descriptor instead.
func (*CreateFollowUpRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{10}
}

func (x *CreateFollowUpRequest) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *CreateFollowUpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateFollowUpRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateFollowUpRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type CreateFollowUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowUp      *FollowUp              `protobuf:"bytes,1,opt,name=follow_up,json=followUp,proto3" json:"follow_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFollowUpResponse) Reset() {
	*x = CreateFollowUpResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowUpResponse) ProtoMessage() {}

func (x *CreateFollowUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowUpResponse.ProtoReflect.Descriptor instead.
func (*CreateFollowUpResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{11}
}

func (x *CreateFollowUpResponse) GetFollowUp() *FollowUp {
	if x != nil {
		return x.FollowUp
	}
	return nil
}

type ListFollowUpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SolutionId    string                 `protobuf:"bytes,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowUpsRequest) Reset() {
	*x = ListFollowUpsRequest{}
	mi := &file_solution_v1_solution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowUpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowUpsRequest) ProtoMessage() {}

func (x *ListFollowUpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowUpsRequest.ProtoReflect.Descriptor instead.
func (*ListFollowUpsRequest) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{12}
}

func (x *ListFollowUpsRequest) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *ListFollowUpsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListFollowUpsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFollowUpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowUps     []*FollowUp            `protobuf:"bytes,1,rep,name=follow_ups,json=followUps,proto3" json:"follow_ups,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowUpsResponse) Reset() {
	*x = ListFollowUpsResponse{}
	mi := &file_solution_v1_solution_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowUpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowUpsResponse) ProtoMessage() {}

func (x *ListFollowUpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowUpsResponse.ProtoReflect.Descriptor instead.
func (*ListFollowUpsResponse) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{13}
}

func (x *ListFollowUpsResponse) GetFollowUps() []*FollowUp {
	if x != nil {
		return x.FollowUps
	}
	return nil
}

func (x *ListFollowUpsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Solution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	MentorId      string                 `protobuf:"bytes,3,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Upvotes       int32                  `protobuf:"varint,6,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	Downvotes     int32                  `protobuf:"varint,7,opt,name=downvotes,proto3" json:"downvotes,omitempty"`
	IsAccepted    bool                   `protobuf:"varint,8,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solution) Reset() {
	*x = Solution{}
	mi := &file_solution_v1_solution_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solution) ProtoMessage() {}

func (x *Solution) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solution.ProtoReflect.Descriptor instead.
func (*Solution) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{14}
}

func (x *Solution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Solution) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Solution) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *Solution) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Solution) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Solution) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *Solution) GetDownvotes() int32 {
	if x != nil {
		return x.Downvotes
	}
	return 0
}

func (x *Solution) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *Solution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Solution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FollowUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SolutionId    string                 `protobuf:"bytes,2,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUp) Reset() {
	*x = FollowUp{}
	mi := &file_solution_v1_solution_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUp) ProtoMessage() {}

func (x *FollowUp) ProtoReflect() protoreflect.Message {
	mi := &file_solution_v1_solution_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUp.ProtoReflect.Descriptor instead.
func (*FollowUp) Descriptor() ([]byte, []int) {
	return file_solution_v1_solution_proto_rawDescGZIP(), []int{15}
}

func (x *FollowUp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FollowUp) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *FollowUp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowUp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FollowUp) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *FollowUp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_solution_v1_solution_proto protoreflect.FileDescriptor

const file_solution_v1_solution_proto_rawDesc = "" +
	"\n" +
	"\x1asolution/v1/solution.proto\x12\vsolution.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\x15CreateSolutionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1b\n" +
	"\tmentor_id\x18\x02 \x01(\tR\bmentorId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x04 \x03(\tR\timageUrls\"K\n" +
	"\x16CreateSolutionResponse\x121\n" +
	"\bsolution\x18\x01 \x01(\v2\x15.solution.v1.SolutionR\bsolution\"9\n" +
	"\x16GetSolutionByIdRequest\x12\x1f\n" +
	"\vsolution_id\x18\x01 \x01(\tR\n" +
	"solutionId\"L\n" +
	"\x17GetSolutionByIdResponse\x121\n" +
	"\bsolution\x18\x01 \x01(\v2\x15.solution.v1.SolutionR\bsolution\"}\n" +
	"\x1eListSolutionsByQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"~\n" +
	"\x1fListSolutionsByQuestionResponse\x123\n" +
	"\tsolutions\x18\x01 \x03(\v2\x15.solution.v1.SolutionR\tsolutions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"z\n" +
	"\x13VoteSolutionRequest\x12\x1f\n" +
	"\vsolution_id\x18\x01 \x01(\tR\n" +
	"solutionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x04vote\x18\x03 \x01(\x0e2\x15.solution.v1.VoteTypeR\x04vote\"N\n" +
	"\x14VoteSolutionResponse\x12\x18\n" +
	"\aupvotes\x18\x01 \x01(\x05R\aupvotes\x12\x1c\n" +
	"\tdownvotes\x18\x02 \x01(\x05R\tdownvotes\"W\n" +
	"\x15AcceptSolutionRequest\x12\x1f\n" +
	"\vsolution_id\x18\x01 \x01(\tR\n" +
	"solutionId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"4\n" +
	"\x16AcceptSolutionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x8a\x01\n" +
	"\x15CreateFollowUpRequest\x12\x1f\n" +
	"\vsolution_id\x18\x01 \x01(\tR\n" +
	"solutionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x04 \x03(\tR\timageUrls\"L\n" +
	"\x16CreateFollowUpResponse\x122\n" +
	"\tfollow_up\x18\x01 \x01(\v2\x15.solution.v1.FollowUpR\bfollowUp\"s\n" +
	"\x14ListFollowUpsRequest\x12\x1f\n" +
	"\vsolution_id\x18\x01 \x01(\tR\n" +
	"solutionId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"u\n" +
	"\x15ListFollowUpsResponse\x124\n" +
	"\n" +
	"follow_ups\x18\x01 \x03(\v2\x15.solution.v1.FollowUpR\tfollowUps\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe8\x02\n" +
	"\bSolution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12\x1b\n" +
	"\tmentor_id\x18\x03 \x01(\tR\bmentorId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x12\x18\n" +
	"\aupvotes\x18\x06 \x01(\x05R\aupvotes\x12\x1c\n" +
	"\tdownvotes\x18\a \x01(\x05R\tdownvotes\x12\x1f\n" +
	"\vis_accepted\x18\b \x01(\bR\n" +
	"isAccepted\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc8\x01\n" +
	"\bFollowUp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsolution_id\x18\x02 \x01(\tR\n" +
	"solutionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*K\n" +
	"\bVoteType\x12\x19\n" +
	"\x15VOTE_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVOTE_TYPE_UP\x10\x01\x12\x12\n" +
	"\x0eVOTE_TYPE_DOWN\x10\x022\xa3\x05\n" +
	"\x0fSolutionService\x12Y\n" +
	"\x0eCreateSolution\x12\".solution.v1.CreateSolutionRequest\x1a#.solution.v1.CreateSolutionResponse\x12\\\n" +
	"\x0fGetSolutionById\x12#.solution.v1.GetSolutionByIdRequest\x1a$.solution.v1.GetSolutionByIdResponse\x12t\n" +
	"\x17ListSolutionsByQuestion\x12+.solution.v1.ListSolutionsByQuestionRequest\x1a,.solution.v1.ListSolutionsByQuestionResponse\x12S\n" +
	"\fVoteSolution\x12 .solution.v1.VoteSolutionRequest\x1a!.solution.v1.VoteSolutionResponse\x12Y\n" +
	"\x0eAcceptSolution\x12\".solution.v1.AcceptSolutionRequest\x1a#.solution.v1.AcceptSolutionResponse\x12Y\n" +
	"\x0eCreateFollowUp\x12\".solution.v1.CreateFollowUpRequest\x1a#.solution.v1.CreateFollowUpResponse\x12V\n" +
	"\rListFollowUps\x12!.solution.v1.ListFollowUpsRequest\x1a\".solution.v1.ListFollowUpsResponseB!Z\x1fpreppi.com/proto/solution/v1;v1b\x06proto3"

var (
	file_solution_v1_solution_proto_rawDescOnce sync.Once
	file_solution_v1_solution_proto_rawDescData []byte
)

func file_solution_v1_solution_proto_rawDescGZIP() []byte {
	file_solution_v1_solution_proto_rawDescOnce.Do(func() {
		file_solution_v1_solution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_solution_v1_solution_proto_rawDesc), len(file_solution_v1_solution_proto_rawDesc)))
	})
	return file_solution_v1_solution_proto_rawDescData
}

var file_solution_v1_solution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_solution_v1_solution_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_solution_v1_solution_proto_goTypes = []any{
	(VoteType)(0),                           // 0: solution.v1.VoteType
	(*CreateSolutionRequest)(nil),           // 1: solution.v1.CreateSolutionRequest
	(*CreateSolutionResponse)(nil),          // 2: solution.v1.CreateSolutionResponse
	(*GetSolutionByIdRequest)(nil),          // 3: solution.v1.GetSolutionByIdRequest
	(*GetSolutionByIdResponse)(nil),         // 4: solution.v1.GetSolutionByIdResponse
	(*ListSolutionsByQuestionRequest)(nil),  // 5: solution.v1.ListSolutionsByQuestionRequest
	(*ListSolutionsByQuestionResponse)(nil), // 6: solution.v1.ListSolutionsByQuestionResponse
	(*VoteSolutionRequest)(nil),             // 7: solution.v1.VoteSolutionRequest
	(*VoteSolutionResponse)(nil),            // 8: solution.v1.VoteSolutionResponse
	(*AcceptSolutionRequest)(nil),           // 9: solution.v1.AcceptSolutionRequest
	(*AcceptSolutionResponse)(nil),          // 10: solution.v1.AcceptSolutionResponse
	(*CreateFollowUpRequest)(nil),           // 11: solution.v1.CreateFollowUpRequest
	(*CreateFollowUpResponse)(nil),          // 12: solution.v1.CreateFollowUpResponse
	(*ListFollowUpsRequest)(nil),            // 13: solution.v1.ListFollowUpsRequest
	(*ListFollowUpsResponse)(nil),           // 14: solution.v1.ListFollowUpsResponse
	(*Solution)(nil),                        // 15: solution.v1.Solution
	(*FollowUp)(nil),                        // 16: solution.v1.FollowUp
	(*timestamppb.Timestamp)(nil),           // 17: google.protobuf.Timestamp
}
var file_solution_v1_solution_proto_depIdxs = []int32{
	15, // 0: solution.v1.CreateSolutionResponse.solution:type_name -> solution.v1.Solution
	15, // 1: solution.v1.GetSolutionByIdResponse.solution:type_name -> solution.v1.Solution
	15, // 2: solution.v1.ListSolutionsByQuestionResponse.solutions:type_name -> solution.v1.Solution
	0,  // 3: solution.v1.VoteSolutionRequest.vote:type_name -> solution.v1.VoteType
	16, // 4: solution.v1.CreateFollowUpResponse.follow_up:type_name -> solution.v1.FollowUp
	16, // 5: solution.v1.ListFollowUpsResponse.follow_ups:type_name -> solution.v1.FollowUp
	17, // 6: solution.v1.Solution.created_at:type_name -> google.protobuf.Timestamp
	17, // 7: solution.v1.Solution.updated_at:type_name -> google.protobuf.Timestamp
	17, // 8: solution.v1.FollowUp.created_at:type_name -> google.protobuf.Timestamp
	1,  // 9: solution.v1.SolutionService.CreateSolution:input_type -> solution.v1.CreateSolutionRequest
	3,  // 10: solution.v1.SolutionService.GetSolutionById:input_type -> solution.v1.GetSolutionByIdRequest
	5,  // 11: solution.v1.SolutionService.ListSolutionsByQuestion:input_type -> solution.v1.ListSolutionsByQuestionRequest
	7,  // 12: solution.v1.SolutionService.VoteSolution:input_type -> solution.v1.VoteSolutionRequest
	9,  // 13: solution.v1.SolutionService.AcceptSolution:input_type -> solution.v1.AcceptSolutionRequest
	11, // 14: solution.v1.SolutionService.CreateFollowUp:input_type -> solution.v1.CreateFollowUpRequest
	13, // 15: solution.v1.SolutionService.ListFollowUps:input_type -> solution.v1.ListFollowUpsRequest
	2,  // 16: solution.v1.SolutionService.CreateSolution:output_type -> solution.v1.CreateSolutionResponse
	4,  // 17: solution.v1.SolutionService.GetSolutionById:output_type -> solution.v1.GetSolutionByIdResponse
	6,  // 18: solution.v1.SolutionService.ListSolutionsByQuestion:output_type -> solution.v1.ListSolutionsByQuestionResponse
	8,  // 19: solution.v1.SolutionService.VoteSolution:output_type -> solution.v1.VoteSolutionResponse
	10, // 20: solution.v1.SolutionService.AcceptSolution:output_type -> solution.v1.AcceptSolutionResponse
	12, // 21: solution.v1.SolutionService.CreateFollowUp:output_type -> solution.v1.CreateFollowUpResponse
	14, // 22: solution.v1.SolutionService.ListFollowUps:output_type -> solution.v1.ListFollowUpsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_solution_v1_solution_proto_init() }
func file_solution_v1_solution_proto_init() {
	if File_solution_v1_solution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_solution_v1_solution_proto_rawDesc), len(file_solution_v1_solution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_solution_v1_solution_proto_goTypes,
		DependencyIndexes: file_solution_v1_solution_proto_depIdxs,
		EnumInfos:         file_solution_v1_solution_proto_enumTypes,
		MessageInfos:      file_solution_v1_solution_proto_msgTypes,
	}.Build()
	File_solution_v1_solution_proto = out.File
	file_solution_v1_solution_proto_goTypes = nil
	file_solution_v1_solution_proto_depIdxs = nil
}
