// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: knowledgebase/v1/knowledgebase.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeBaseService_SearchKB_FullMethodName         = "/knowledgebase.v1.KnowledgeBaseService/SearchKB"
	KnowledgeBaseService_GetArticle_FullMethodName       = "/knowledgebase.v1.KnowledgeBaseService/GetArticle"
	KnowledgeBaseService_GetRelatedTopics_FullMethodName = "/knowledgebase.v1.KnowledgeBaseService/GetRelatedTopics"
	KnowledgeBaseService_SuggestKeywords_FullMethodName  = "/knowledgebase.v1.KnowledgeBaseService/SuggestKeywords"
)

// KnowledgeBaseServiceClient is the client API for KnowledgeBaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeBaseServiceClient interface {
	SearchKB(ctx context.Context, in *SearchKBRequest, opts ...grpc.CallOption) (*SearchKBResponse, error)
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
	GetRelatedTopics(ctx context.Context, in *GetRelatedTopicsRequest, opts ...grpc.CallOption) (*GetRelatedTopicsResponse, error)
	SuggestKeywords(ctx context.Context, in *SuggestKeywordsRequest, opts ...grpc.CallOption) (*SuggestKeywordsResponse, error)
}

type knowledgeBaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeBaseServiceClient(cc grpc.ClientConnInterface) KnowledgeBaseServiceClient {
	return &knowledgeBaseServiceClient{cc}
}

func (c *knowledgeBaseServiceClient) SearchKB(ctx context.Context, in *SearchKBRequest, opts ...grpc.CallOption) (*SearchKBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKBResponse)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SearchKB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleResponse)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetRelatedTopics(ctx context.Context, in *GetRelatedTopicsRequest, opts ...grpc.CallOption) (*GetRelatedTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelatedTopicsResponse)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetRelatedTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SuggestKeywords(ctx context.Context, in *SuggestKeywordsRequest, opts ...grpc.CallOption) (*SuggestKeywordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestKeywordsResponse)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SuggestKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeBaseServiceServer is the server API for KnowledgeBaseService service.
// All implementations should embed UnimplementedKnowledgeBaseServiceServer
// for forward compatibility.
type KnowledgeBaseServiceServer interface {
	SearchKB(context.Context, *SearchKBRequest) (*SearchKBResponse, error)
	GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error)
	GetRelatedTopics(context.Context, *GetRelatedTopicsRequest) (*GetRelatedTopicsResponse, error)
	SuggestKeywords(context.Context, *SuggestKeywordsRequest) (*SuggestKeywordsResponse, error)
}

// UnimplementedKnowledgeBaseServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeBaseServiceServer struct{}

func (UnimplementedKnowledgeBaseServiceServer) SearchKB(context.Context, *SearchKBRequest) (*SearchKBResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKB not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetRelatedTopics(context.Context, *GetRelatedTopicsRequest) (*GetRelatedTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelatedTopics not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SuggestKeywords(context.Context, *SuggestKeywordsRequest) (*SuggestKeywordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestKeywords not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) testEmbeddedByValue() {}

// UnsafeKnowledgeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeBaseServiceServer will
// result in compilation errors.
type UnsafeKnowledgeBaseServiceServer interface {
	mustEmbedUnimplementedKnowledgeBaseServiceServer()
}

func RegisterKnowledgeBaseServiceServer(s grpc.ServiceRegistrar, srv KnowledgeBaseServiceServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeBaseService_ServiceDesc, srv)
}

func _KnowledgeBaseService_SearchKB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SearchKB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SearchKB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SearchKB(ctx, req.(*SearchKBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetRelatedTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelatedTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetRelatedTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetRelatedTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetRelatedTopics(ctx, req.(*GetRelatedTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SuggestKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestKeywordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SuggestKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SuggestKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SuggestKeywords(ctx, req.(*SuggestKeywordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeBaseService_ServiceDesc is the grpc.ServiceDesc for KnowledgeBaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeBaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledgebase.v1.KnowledgeBaseService",
	HandlerType: (*KnowledgeBaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchKB",
			Handler:    _KnowledgeBaseService_SearchKB_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _KnowledgeBaseService_GetArticle_Handler,
		},
		{
			MethodName: "GetRelatedTopics",
			Handler:    _KnowledgeBaseService_GetRelatedTopics_Handler,
		},
		{
			MethodName: "SuggestKeywords",
			Handler:    _KnowledgeBaseService_SuggestKeywords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledgebase/v1/knowledgebase.proto",
}
