// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: knowledgebase/v1/knowledgebase.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchKBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKBRequest) Reset() {
	*x = SearchKBRequest{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKBRequest) ProtoMessage() {}

func (x *SearchKBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKBRequest.ProtoReflect.Descriptor instead.
func (*SearchKBRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{0}
}

func (x *SearchKBRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchKBRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SearchKBRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchKBRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchKBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKBResponse) Reset() {
	*x = SearchKBResponse{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKBResponse) ProtoMessage() {}

func (x *SearchKBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKBResponse.ProtoReflect.Descriptor instead.
func (*SearchKBResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{1}
}

func (x *SearchKBResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *SearchKBResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	FullText      string                 `protobuf:"bytes,2,opt,name=full_text,json=fullText,proto3" json:"full_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *GetArticleResponse) GetFullText() string {
	if x != nil {
		return x.FullText
	}
	return ""
}

type GetRelatedTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedTopicsRequest) Reset() {
	*x = GetRelatedTopicsRequest{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedTopicsRequest) ProtoMessage() {}

func (x *GetRelatedTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetRelatedTopicsRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{4}
}

func (x *GetRelatedTopicsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetRelatedTopicsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type GetRelatedTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedTopicsResponse) Reset() {
	*x = GetRelatedTopicsResponse{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedTopicsResponse) ProtoMessage() {}

func (x *GetRelatedTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetRelatedTopicsResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{5}
}

func (x *GetRelatedTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type SuggestKeywordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestKeywordsRequest) Reset() {
	*x = SuggestKeywordsRequest{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestKeywordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestKeywordsRequest) ProtoMessage() {}

func (x *SuggestKeywordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestKeywordsRequest.ProtoReflect.Descriptor instead.
func (*SuggestKeywordsRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestKeywordsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SuggestKeywordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestKeywordsResponse) Reset() {
	*x = SuggestKeywordsResponse{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestKeywordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestKeywordsResponse) ProtoMessage() {}

func (x *SuggestKeywordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestKeywordsResponse.ProtoReflect.Descriptor instead.
func (*SuggestKeywordsResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestKeywordsResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Upvotes       int32                  `protobuf:"varint,6,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{8}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Article) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	ArticleCount  int32                  `protobuf:"varint,4,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_v1_knowledgebase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP(), []int{9}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Topic) GetArticleCount() int32 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

var File_knowledgebase_v1_knowledgebase_proto protoreflect.FileDescriptor

const file_knowledgebase_v1_knowledgebase_proto_rawDesc = "" +
	"\n" +
	"$knowledgebase/v1/knowledgebase.proto\x12\x10knowledgebase.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x0fSearchKBRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"q\n" +
	"\x10SearchKBResponse\x125\n" +
	"\barticles\x18\x01 \x03(\v2\x19.knowledgebase.v1.ArticleR\barticles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x11GetArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"f\n" +
	"\x12GetArticleResponse\x123\n" +
	"\aarticle\x18\x01 \x01(\v2\x19.knowledgebase.v1.ArticleR\aarticle\x12\x1b\n" +
	"\tfull_text\x18\x02 \x01(\tR\bfullText\"I\n" +
	"\x17GetRelatedTopicsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"K\n" +
	"\x18GetRelatedTopicsResponse\x12/\n" +
	"\x06topics\x18\x01 \x03(\v2\x17.knowledgebase.v1.TopicR\x06topics\".\n" +
	"\x16SuggestKeywordsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"5\n" +
	"\x17SuggestKeywordsResponse\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\"\xce\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x18\n" +
	"\aupvotes\x18\x06 \x01(\x05R\aupvotes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"j\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12#\n" +
	"\rarticle_count\x18\x04 \x01(\x05R\farticleCount2\x95\x03\n" +
	"\x14KnowledgeBaseService\x12Q\n" +
	"\bSearchKB\x12!.knowledgebase.v1.SearchKBRequest\x1a\".knowledgebase.v1.SearchKBResponse\x12W\n" +
	"\n" +
	"GetArticle\x12#.knowledgebase.v1.GetArticleRequest\x1a$.knowledgebase.v1.GetArticleResponse\x12i\n" +
	"\x10GetRelatedTopics\x12).knowledgebase.v1.GetRelatedTopicsRequest\x1a*.knowledgebase.v1.GetRelatedTopicsResponse\x12f\n" +
	"\x0fSuggestKeywords\x12(.knowledgebase.v1.SuggestKeywordsRequest\x1a).knowledgebase.v1.SuggestKeywordsResponseB&Z$preppi.com/proto/knowledgebase/v1;v1b\x06proto3"

var (
	file_knowledgebase_v1_knowledgebase_proto_rawDescOnce sync.Once
	file_knowledgebase_v1_knowledgebase_proto_rawDescData []byte
)

func file_knowledgebase_v1_knowledgebase_proto_rawDescGZIP() []byte {
	file_knowledgebase_v1_knowledgebase_proto_rawDescOnce.Do(func() {
		file_knowledgebase_v1_knowledgebase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledgebase_v1_knowledgebase_proto_rawDesc), len(file_knowledgebase_v1_knowledgebase_proto_rawDesc)))
	})
	return file_knowledgebase_v1_knowledgebase_proto_rawDescData
}

var file_knowledgebase_v1_knowledgebase_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_knowledgebase_v1_knowledgebase_proto_goTypes = []any{
	(*SearchKBRequest)(nil),          // 0: knowledgebase.v1.SearchKBRequest
	(*SearchKBResponse)(nil),         // 1: knowledgebase.v1.SearchKBResponse
	(*GetArticleRequest)(nil),        // 2: knowledgebase.v1.GetArticleRequest
	(*GetArticleResponse)(nil),       // 3: knowledgebase.v1.GetArticleResponse
	(*GetRelatedTopicsRequest)(nil),  // 4: knowledgebase.v1.GetRelatedTopicsRequest
	(*GetRelatedTopicsResponse)(nil), // 5: knowledgebase.v1.GetRelatedTopicsResponse
	(*SuggestKeywordsRequest)(nil),   // 6: knowledgebase.v1.SuggestKeywordsRequest
	(*SuggestKeywordsResponse)(nil),  // 7: knowledgebase.v1.SuggestKeywordsResponse
	(*Article)(nil),                  // 8: knowledgebase.v1.Article
	(*Topic)(nil),                    // 9: knowledgebase.v1.Topic
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_knowledgebase_v1_knowledgebase_proto_depIdxs = []int32{
	8,  // 0: knowledgebase.v1.SearchKBResponse.articles:type_name -> knowledgebase.v1.Article
	8,  // 1: knowledgebase.v1.GetArticleResponse.article:type_name -> knowledgebase.v1.Article
	9,  // 2: knowledgebase.v1.GetRelatedTopicsResponse.topics:type_name -> knowledgebase.v1.Topic
	10, // 3: knowledgebase.v1.Article.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: knowledgebase.v1.KnowledgeBaseService.SearchKB:input_type -> knowledgebase.v1.SearchKBRequest
	2,  // 5: knowledgebase.v1.KnowledgeBaseService.GetArticle:input_type -> knowledgebase.v1.GetArticleRequest
	4,  // 6: knowledgebase.v1.KnowledgeBaseService.GetRelatedTopics:input_type -> knowledgebase.v1.GetRelatedTopicsRequest
	6,  // 7: knowledgebase.v1.KnowledgeBaseService.SuggestKeywords:input_type -> knowledgebase.v1.SuggestKeywordsRequest
	1,  // 8: knowledgebase.v1.KnowledgeBaseService.SearchKB:output_type -> knowledgebase.v1.SearchKBResponse
	3,  // 9: knowledgebase.v1.KnowledgeBaseService.GetArticle:output_type -> knowledgebase.v1.GetArticleResponse
	5,  // 10: knowledgebase.v1.KnowledgeBaseService.GetRelatedTopics:output_type -> knowledgebase.v1.GetRelatedTopicsResponse
	7,  // 11: knowledgebase.v1.KnowledgeBaseService.SuggestKeywords:output_type -> knowledgebase.v1.SuggestKeywordsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_knowledgebase_v1_knowledgebase_proto_init() }
func file_knowledgebase_v1_knowledgebase_proto_init() {
	if File_knowledgebase_v1_knowledgebase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledgebase_v1_knowledgebase_proto_rawDesc), len(file_knowledgebase_v1_knowledgebase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledgebase_v1_knowledgebase_proto_goTypes,
		DependencyIndexes: file_knowledgebase_v1_knowledgebase_proto_depIdxs,
		MessageInfos:      file_knowledgebase_v1_knowledgebase_proto_msgTypes,
	}.Build()
	File_knowledgebase_v1_knowledgebase_proto = out.File
	file_knowledgebase_v1_knowledgebase_proto_goTypes = nil
	file_knowledgebase_v1_knowledgebase_proto_depIdxs = nil
}
