// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: question/v1/question.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionStatus int32

const (
	QuestionStatus_QUESTION_STATUS_UNSPECIFIED QuestionStatus = 0
	QuestionStatus_QUESTION_STATUS_OPEN        QuestionStatus = 1
	QuestionStatus_QUESTION_STATUS_ASSIGNED    QuestionStatus = 2
	QuestionStatus_QUESTION_STATUS_IN_PROGRESS QuestionStatus = 3
	QuestionStatus_QUESTION_STATUS_ANSWERED    QuestionStatus = 4
	QuestionStatus_QUESTION_STATUS_ESCALATED   QuestionStatus = 5
)

// Enum value maps for QuestionStatus.
var (
	QuestionStatus_name = map[int32]string{
		0: "QUESTION_STATUS_UNSPECIFIED",
		1: "QUESTION_STATUS_OPEN",
		2: "QUESTION_STATUS_ASSIGNED",
		3: "QUESTION_STATUS_IN_PROGRESS",
		4: "QUESTION_STATUS_ANSWERED",
		5: "QUESTION_STATUS_ESCALATED",
	}
	QuestionStatus_value = map[string]int32{
		"QUESTION_STATUS_UNSPECIFIED": 0,
		"QUESTION_STATUS_OPEN":        1,
		"QUESTION_STATUS_ASSIGNED":    2,
		"QUESTION_STATUS_IN_PROGRESS": 3,
		"QUESTION_STATUS_ANSWERED":    4,
		"QUESTION_STATUS_ESCALATED":   5,
	}
)

func (x QuestionStatus) Enum() *QuestionStatus {
	p := new(QuestionStatus)
	*p = x
	return p
}

func (x QuestionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_question_v1_question_proto_enumTypes[0].Descriptor()
}

func (QuestionStatus) Type() protoreflect.EnumType {
	return &file_question_v1_question_proto_enumTypes[0]
}

func (x QuestionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionStatus.Descriptor instead.
func (QuestionStatus) EnumDescriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{0}
}

type Urgency int32

const (
	Urgency_URGENCY_UNSPECIFIED Urgency = 0
	Urgency_URGENCY_LOW         Urgency = 1
	Urgency_URGENCY_NORMAL      Urgency = 2
	Urgency_URGENCY_URGENT      Urgency = 3
)

// Enum value maps for Urgency.
var (
	Urgency_name = map[int32]string{
		0: "URGENCY_UNSPECIFIED",
		1: "URGENCY_LOW",
		2: "URGENCY_NORMAL",
		3: "URGENCY_URGENT",
	}
	Urgency_value = map[string]int32{
		"URGENCY_UNSPECIFIED": 0,
		"URGENCY_LOW":         1,
		"URGENCY_NORMAL":      2,
		"URGENCY_URGENT":      3,
	}
)

func (x Urgency) Enum() *Urgency {
	p := new(Urgency)
	*p = x
	return p
}

func (x Urgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Urgency) Descriptor() protoreflect.EnumDescriptor {
	return file_question_v1_question_proto_enumTypes[1].Descriptor()
}

func (Urgency) Type() protoreflect.EnumType {
	return &file_question_v1_question_proto_enumTypes[1]
}

func (x Urgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Urgency.Descriptor instead.
func (Urgency) EnumDescriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{1}
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Urgency       Urgency                `protobuf:"varint,6,opt,name=urgency,proto3,enum=question.v1.Urgency" json:"urgency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_question_v1_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuestionRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateQuestionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateQuestionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateQuestionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateQuestionRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *CreateQuestionRequest) GetUrgency() Urgency {
	if x != nil {
		return x.Urgency
	}
	return Urgency_URGENCY_UNSPECIFIED
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Status        QuestionStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=question.v1.QuestionStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_question_v1_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuestionResponse) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *CreateQuestionResponse) GetStatus() QuestionStatus {
	if x != nil {
		return x.Status
	}
	return QuestionStatus_QUESTION_STATUS_UNSPECIFIED
}

func (x *CreateQuestionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetQuestionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionByIdRequest) Reset() {
	*x = GetQuestionByIdRequest{}
	mi := &file_question_v1_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionByIdRequest) ProtoMessage() {}

func (x *GetQuestionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionByIdRequest) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuestionByIdRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type GetQuestionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Solution      *SolutionSummary       `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	Comments      []*CommentSummary      `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionByIdResponse) Reset() {
	*x = GetQuestionByIdResponse{}
	mi := &file_question_v1_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionByIdResponse) ProtoMessage() {}

func (x *GetQuestionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionByIdResponse) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuestionByIdResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *GetQuestionByIdResponse) GetSolution() *SolutionSummary {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *GetQuestionByIdResponse) GetComments() []*CommentSummary {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ListQuestionsByStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsByStudentRequest) Reset() {
	*x = ListQuestionsByStudentRequest{}
	mi := &file_question_v1_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsByStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsByStudentRequest) ProtoMessage() {}

func (x *ListQuestionsByStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsByStudentRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionsByStudentRequest) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{4}
}

func (x *ListQuestionsByStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ListQuestionsByStudentRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListQuestionsByStudentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListQuestionsByStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsByStudentResponse) Reset() {
	*x = ListQuestionsByStudentResponse{}
	mi := &file_question_v1_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsByStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsByStudentResponse) ProtoMessage() {}

func (x *ListQuestionsByStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsByStudentResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionsByStudentResponse) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{5}
}

func (x *ListQuestionsByStudentResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *ListQuestionsByStudentResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateQuestionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Status        QuestionStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=question.v1.QuestionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionStatusRequest) Reset() {
	*x = UpdateQuestionStatusRequest{}
	mi := &file_question_v1_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionStatusRequest) ProtoMessage() {}

func (x *UpdateQuestionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionStatusRequest) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateQuestionStatusRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *UpdateQuestionStatusRequest) GetStatus() QuestionStatus {
	if x != nil {
		return x.Status
	}
	return QuestionStatus_QUESTION_STATUS_UNSPECIFIED
}

type UpdateQuestionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionStatusResponse) Reset() {
	*x = UpdateQuestionStatusResponse{}
	mi := &file_question_v1_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionStatusResponse) ProtoMessage() {}

func (x *UpdateQuestionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionStatusResponse) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateQuestionStatusResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type SearchQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsRequest) Reset() {
	*x = SearchQuestionsRequest{}
	mi := &file_question_v1_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsRequest) ProtoMessage() {}

func (x *SearchQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsRequest.ProtoReflect.Descriptor instead.
func (*SearchQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{8}
}

func (x *SearchQuestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchQuestionsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SearchQuestionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchQuestionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsResponse) Reset() {
	*x = SearchQuestionsResponse{}
	mi := &file_question_v1_question_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsResponse) ProtoMessage() {}

func (x *SearchQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SearchQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{9}
}

func (x *SearchQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *SearchQuestionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Urgency       Urgency                `protobuf:"varint,6,opt,name=urgency,proto3,enum=question.v1.Urgency" json:"urgency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_question_v1_question_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *UpdateQuestionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateQuestionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UpdateQuestionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateQuestionRequest) GetUrgency() Urgency {
	if x != nil {
		return x.Urgency
	}
	return Urgency_URGENCY_UNSPECIFIED
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_question_v1_question_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,3,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Urgency       Urgency                `protobuf:"varint,8,opt,name=urgency,proto3,enum=question.v1.Urgency" json:"urgency,omitempty"`
	Status        QuestionStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=question.v1.QuestionStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_question_v1_question_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{12}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Question) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *Question) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Question) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Question) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Question) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Question) GetUrgency() Urgency {
	if x != nil {
		return x.Urgency
	}
	return Urgency_URGENCY_UNSPECIFIED
}

func (x *Question) GetStatus() QuestionStatus {
	if x != nil {
		return x.Status
	}
	return QuestionStatus_QUESTION_STATUS_UNSPECIFIED
}

func (x *Question) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Question) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SolutionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MentorId      string                 `protobuf:"bytes,2,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Upvotes       int32                  `protobuf:"varint,4,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	IsAccepted    bool                   `protobuf:"varint,5,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolutionSummary) Reset() {
	*x = SolutionSummary{}
	mi := &file_question_v1_question_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolutionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolutionSummary) ProtoMessage() {}

func (x *SolutionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolutionSummary.ProtoReflect.Descriptor instead.
func (*SolutionSummary) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{13}
}

func (x *SolutionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SolutionSummary) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *SolutionSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SolutionSummary) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *SolutionSummary) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *SolutionSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CommentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentSummary) Reset() {
	*x = CommentSummary{}
	mi := &file_question_v1_question_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentSummary) ProtoMessage() {}

func (x *CommentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_question_v1_question_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentSummary.ProtoReflect.Descriptor instead.
func (*CommentSummary) Descriptor() ([]byte, []int) {
	return file_question_v1_question_proto_rawDescGZIP(), []int{14}
}

func (x *CommentSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommentSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommentSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_question_v1_question_proto protoreflect.FileDescriptor

const file_question_v1_question_proto_rawDesc = "" +
	"\n" +
	"\x1aquestion/v1/question.proto\x12\vquestion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xd7\x01\n" +
	"\x15CreateQuestionRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x12.\n" +
	"\aurgency\x18\x06 \x01(\x0e2\x14.question.v1.UrgencyR\aurgency\"\xa9\x01\n" +
	"\x16CreateQuestionResponse\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.question.v1.QuestionStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\x16GetQuestionByIdRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"\xbf\x01\n" +
	"\x17GetQuestionByIdResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.question.v1.QuestionR\bquestion\x128\n" +
	"\bsolution\x18\x02 \x01(\v2\x1c.question.v1.SolutionSummaryR\bsolution\x127\n" +
	"\bcomments\x18\x03 \x03(\v2\x1b.question.v1.CommentSummaryR\bcomments\"z\n" +
	"\x1dListQuestionsByStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"}\n" +
	"\x1eListQuestionsByStudentResponse\x123\n" +
	"\tquestions\x18\x01 \x03(\v2\x15.question.v1.QuestionR\tquestions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"s\n" +
	"\x1bUpdateQuestionStatusRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.question.v1.QuestionStatusR\x06status\"Q\n" +
	"\x1cUpdateQuestionStatusResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.question.v1.QuestionR\bquestion\"\x84\x01\n" +
	"\x16SearchQuestionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"v\n" +
	"\x17SearchQuestionsResponse\x123\n" +
	"\tquestions\x18\x01 \x03(\v2\x15.question.v1.QuestionR\tquestions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xf7\x01\n" +
	"\x15UpdateQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12.\n" +
	"\aurgency\x18\x06 \x01(\x0e2\x14.question.v1.UrgencyR\aurgency\"K\n" +
	"\x16UpdateQuestionResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.question.v1.QuestionR\bquestion\"\xa6\x03\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1f\n" +
	"\vassignee_id\x18\x03 \x01(\tR\n" +
	"assigneeId\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x12.\n" +
	"\aurgency\x18\b \x01(\x0e2\x14.question.v1.UrgencyR\aurgency\x123\n" +
	"\x06status\x18\t \x01(\x0e2\x1b.question.v1.QuestionStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd6\x01\n" +
	"\x0fSolutionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmentor_id\x18\x02 \x01(\tR\bmentorId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aupvotes\x18\x04 \x01(\x05R\aupvotes\x12\x1f\n" +
	"\vis_accepted\x18\x05 \x01(\bR\n" +
	"isAccepted\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8e\x01\n" +
	"\x0eCommentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\xc7\x01\n" +
	"\x0eQuestionStatus\x12\x1f\n" +
	"\x1bQUESTION_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUESTION_STATUS_OPEN\x10\x01\x12\x1c\n" +
	"\x18QUESTION_STATUS_ASSIGNED\x10\x02\x12\x1f\n" +
	"\x1bQUESTION_STATUS_IN_PROGRESS\x10\x03\x12\x1c\n" +
	"\x18QUESTION_STATUS_ANSWERED\x10\x04\x12\x1d\n" +
	"\x19QUESTION_STATUS_ESCALATED\x10\x05*[\n" +
	"\aUrgency\x12\x17\n" +
	"\x13URGENCY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vURGENCY_LOW\x10\x01\x12\x12\n" +
	"\x0eURGENCY_NORMAL\x10\x02\x12\x12\n" +
	"\x0eURGENCY_URGENT\x10\x032\xe3\x04\n" +
	"\x0fQuestionService\x12Y\n" +
	"\x0eCreateQuestion\x12\".question.v1.CreateQuestionRequest\x1a#.question.v1.CreateQuestionResponse\x12\\\n" +
	"\x0fGetQuestionById\x12#.question.v1.GetQuestionByIdRequest\x1a$.question.v1.GetQuestionByIdResponse\x12q\n" +
	"\x16ListQuestionsByStudent\x12*.question.v1.ListQuestionsByStudentRequest\x1a+.question.v1.ListQuestionsByStudentResponse\x12k\n" +
	"\x14UpdateQuestionStatus\x12(.question.v1.UpdateQuestionStatusRequest\x1a).question.v1.UpdateQuestionStatusResponse\x12\\\n" +
	"\x0fSearchQuestions\x12#.question.v1.SearchQuestionsRequest\x1a$.question.v1.SearchQuestionsResponse\x12Y\n" +
	"\x0eUpdateQuestion\x12\".question.v1.UpdateQuestionRequest\x1a#.question.v1.UpdateQuestionResponseB!Z\x1fpreppi.com/proto/question/v1;v1b\x06proto3"

var (
	file_question_v1_question_proto_rawDescOnce sync.Once
	file_question_v1_question_proto_rawDescData []byte
)

func file_question_v1_question_proto_rawDescGZIP() []byte {
	file_question_v1_question_proto_rawDescOnce.Do(func() {
		file_question_v1_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_question_v1_question_proto_rawDesc), len(file_question_v1_question_proto_rawDesc)))
	})
	return file_question_v1_question_proto_rawDescData
}

var file_question_v1_question_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_question_v1_question_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_question_v1_question_proto_goTypes = []any{
	(QuestionStatus)(0),                    // 0: question.v1.QuestionStatus
	(Urgency)(0),                           // 1: question.v1.Urgency
	(*CreateQuestionRequest)(nil),          // 2: question.v1.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),         // 3: question.v1.CreateQuestionResponse
	(*GetQuestionByIdRequest)(nil),         // 4: question.v1.GetQuestionByIdRequest
	(*GetQuestionByIdResponse)(nil),        // 5: question.v1.GetQuestionByIdResponse
	(*ListQuestionsByStudentRequest)(nil),  // 6: question.v1.ListQuestionsByStudentRequest
	(*ListQuestionsByStudentResponse)(nil), // 7: question.v1.ListQuestionsByStudentResponse
	(*UpdateQuestionStatusRequest)(nil),    // 8: question.v1.UpdateQuestionStatusRequest
	(*UpdateQuestionStatusResponse)(nil),   // 9: question.v1.UpdateQuestionStatusResponse
	(*SearchQuestionsRequest)(nil),         // 10: question.v1.SearchQuestionsRequest
	(*SearchQuestionsResponse)(nil),        // 11: question.v1.SearchQuestionsResponse
	(*UpdateQuestionRequest)(nil),          // 12: question.v1.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),         // 13: question.v1.UpdateQuestionResponse
	(*Question)(nil),                       // 14: question.v1.Question
	(*SolutionSummary)(nil),                // 15: question.v1.SolutionSummary
	(*CommentSummary)(nil),                 // 16: question.v1.CommentSummary
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 18: google.protobuf.FieldMask
}
var file_question_v1_question_proto_depIdxs = []int32{
	1,  // 0: question.v1.CreateQuestionRequest.urgency:type_name -> question.v1.Urgency
	0,  // 1: question.v1.CreateQuestionResponse.status:type_name -> question.v1.QuestionStatus
	17, // 2: question.v1.CreateQuestionResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: question.v1.GetQuestionByIdResponse.question:type_name -> question.v1.Question
	15, // 4: question.v1.GetQuestionByIdResponse.solution:type_name -> question.v1.SolutionSummary
	16, // 5: question.v1.GetQuestionByIdResponse.comments:type_name -> question.v1.CommentSummary
	14, // 6: question.v1.ListQuestionsByStudentResponse.questions:type_name -> question.v1.Question
	0,  // 7: question.v1.UpdateQuestionStatusRequest.status:type_name -> question.v1.QuestionStatus
	14, // 8: question.v1.UpdateQuestionStatusResponse.question:type_name -> question.v1.Question
	14, // 9: question.v1.SearchQuestionsResponse.questions:type_name -> question.v1.Question
	18, // 10: question.v1.UpdateQuestionRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 11: question.v1.UpdateQuestionRequest.urgency:type_name -> question.v1.Urgency
	14, // 12: question.v1.UpdateQuestionResponse.question:type_name -> question.v1.Question
	1,  // 13: question.v1.Question.urgency:type_name -> question.v1.Urgency
	0,  // 14: question.v1.Question.status:type_name -> question.v1.QuestionStatus
	17, // 15: question.v1.Question.created_at:type_name -> google.protobuf.Timestamp
	17, // 16: question.v1.Question.updated_at:type_name -> google.protobuf.Timestamp
	17, // 17: question.v1.SolutionSummary.created_at:type_name -> google.protobuf.Timestamp
	17, // 18: question.v1.CommentSummary.created_at:type_name -> google.protobuf.Timestamp
	2,  // 19: question.v1.QuestionService.CreateQuestion:input_type -> question.v1.CreateQuestionRequest
	4,  // 20: question.v1.QuestionService.GetQuestionById:input_type -> question.v1.GetQuestionByIdRequest
	6,  // 21: question.v1.QuestionService.ListQuestionsByStudent:input_type -> question.v1.ListQuestionsByStudentRequest
	8,  // 22: question.v1.QuestionService.UpdateQuestionStatus:input_type -> question.v1.UpdateQuestionStatusRequest
	10, // 23: question.v1.QuestionService.SearchQuestions:input_type -> question.v1.SearchQuestionsRequest
	12, // 24: question.v1.QuestionService.UpdateQuestion:input_type -> question.v1.UpdateQuestionRequest
	3,  // 25: question.v1.QuestionService.CreateQuestion:output_type -> question.v1.CreateQuestionResponse
	5,  // 26: question.v1.QuestionService.GetQuestionById:output_type -> question.v1.GetQuestionByIdResponse
	7,  // 27: question.v1.QuestionService.ListQuestionsByStudent:output_type -> question.v1.ListQuestionsByStudentResponse
	9,  // 28: question.v1.QuestionService.UpdateQuestionStatus:output_type -> question.v1.UpdateQuestionStatusResponse
	11, // 29: question.v1.QuestionService.SearchQuestions:output_type -> question.v1.SearchQuestionsResponse
	13, // 30: question.v1.QuestionService.UpdateQuestion:output_type -> question.v1.UpdateQuestionResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_question_v1_question_proto_init() }
func file_question_v1_question_proto_init() {
	if File_question_v1_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_question_v1_question_proto_rawDesc), len(file_question_v1_question_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_question_v1_question_proto_goTypes,
		DependencyIndexes: file_question_v1_question_proto_depIdxs,
		EnumInfos:         file_question_v1_question_proto_enumTypes,
		MessageInfos:      file_question_v1_question_proto_msgTypes,
	}.Build()
	File_question_v1_question_proto = out.File
	file_question_v1_question_proto_goTypes = nil
	file_question_v1_question_proto_depIdxs = nil
}
