// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: matching/v1/matching.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingService_AssignMentor_FullMethodName        = "/matching.v1.MatchingService/AssignMentor"
	MatchingService_SkipQuestion_FullMethodName        = "/matching.v1.MatchingService/SkipQuestion"
	MatchingService_GetNextQuestion_FullMethodName     = "/matching.v1.MatchingService/GetNextQuestion"
	MatchingService_GetPendingForMentor_FullMethodName = "/matching.v1.MatchingService/GetPendingForMentor"
	MatchingService_EscalateQuestion_FullMethodName    = "/matching.v1.MatchingService/EscalateQuestion"
)

// MatchingServiceClient is the client API for MatchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingServiceClient interface {
	AssignMentor(ctx context.Context, in *AssignMentorRequest, opts ...grpc.CallOption) (*AssignMentorResponse, error)
	SkipQuestion(ctx context.Context, in *SkipQuestionRequest, opts ...grpc.CallOption) (*SkipQuestionResponse, error)
	GetNextQuestion(ctx context.Context, in *GetNextQuestionRequest, opts ...grpc.CallOption) (*GetNextQuestionResponse, error)
	GetPendingForMentor(ctx context.Context, in *GetPendingForMentorRequest, opts ...grpc.CallOption) (*GetPendingForMentorResponse, error)
	EscalateQuestion(ctx context.Context, in *EscalateQuestionRequest, opts ...grpc.CallOption) (*EscalateQuestionResponse, error)
}

type matchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingServiceClient(cc grpc.ClientConnInterface) MatchingServiceClient {
	return &matchingServiceClient{cc}
}

func (c *matchingServiceClient) AssignMentor(ctx context.Context, in *AssignMentorRequest, opts ...grpc.CallOption) (*AssignMentorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignMentorResponse)
	err := c.cc.Invoke(ctx, MatchingService_AssignMentor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) SkipQuestion(ctx context.Context, in *SkipQuestionRequest, opts ...grpc.CallOption) (*SkipQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkipQuestionResponse)
	err := c.cc.Invoke(ctx, MatchingService_SkipQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetNextQuestion(ctx context.Context, in *GetNextQuestionRequest, opts ...grpc.CallOption) (*GetNextQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNextQuestionResponse)
	err := c.cc.Invoke(ctx, MatchingService_GetNextQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetPendingForMentor(ctx context.Context, in *GetPendingForMentorRequest, opts ...grpc.CallOption) (*GetPendingForMentorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingForMentorResponse)
	err := c.cc.Invoke(ctx, MatchingService_GetPendingForMentor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) EscalateQuestion(ctx context.Context, in *EscalateQuestionRequest, opts ...grpc.CallOption) (*EscalateQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscalateQuestionResponse)
	err := c.cc.Invoke(ctx, MatchingService_EscalateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingServiceServer is the server API for MatchingService service.
// All implementations should embed UnimplementedMatchingServiceServer
// for forward compatibility.
type MatchingServiceServer interface {
	AssignMentor(context.Context, *AssignMentorRequest) (*AssignMentorResponse, error)
	SkipQuestion(context.Context, *SkipQuestionRequest) (*SkipQuestionResponse, error)
	GetNextQuestion(context.Context, *GetNextQuestionRequest) (*GetNextQuestionResponse, error)
	GetPendingForMentor(context.Context, *GetPendingForMentorRequest) (*GetPendingForMentorResponse, error)
	EscalateQuestion(context.Context, *EscalateQuestionRequest) (*EscalateQuestionResponse, error)
}

// UnimplementedMatchingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServiceServer struct{}

func (UnimplementedMatchingServiceServer) AssignMentor(context.Context, *AssignMentorRequest) (*AssignMentorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignMentor not implemented")
}
func (UnimplementedMatchingServiceServer) SkipQuestion(context.Context, *SkipQuestionRequest) (*SkipQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SkipQuestion not implemented")
}
func (UnimplementedMatchingServiceServer) GetNextQuestion(context.Context, *GetNextQuestionRequest) (*GetNextQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextQuestion not implemented")
}
func (UnimplementedMatchingServiceServer) GetPendingForMentor(context.Context, *GetPendingForMentorRequest) (*GetPendingForMentorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingForMentor not implemented")
}
func (UnimplementedMatchingServiceServer) EscalateQuestion(context.Context, *EscalateQuestionRequest) (*EscalateQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EscalateQuestion not implemented")
}
func (UnimplementedMatchingServiceServer) testEmbeddedByValue() {}

// UnsafeMatchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServiceServer will
// result in compilation errors.
type UnsafeMatchingServiceServer interface {
	mustEmbedUnimplementedMatchingServiceServer()
}

func RegisterMatchingServiceServer(s grpc.ServiceRegistrar, srv MatchingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingService_ServiceDesc, srv)
}

func _MatchingService_AssignMentor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignMentorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).AssignMentor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_AssignMentor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).AssignMentor(ctx, req.(*AssignMentorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_SkipQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkipQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).SkipQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_SkipQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).SkipQuestion(ctx, req.(*SkipQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetNextQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetNextQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetNextQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetNextQuestion(ctx, req.(*GetNextQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetPendingForMentor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingForMentorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetPendingForMentor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetPendingForMentor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetPendingForMentor(ctx, req.(*GetPendingForMentorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_EscalateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscalateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).EscalateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_EscalateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).EscalateQuestion(ctx, req.(*EscalateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingService_ServiceDesc is the grpc.ServiceDesc for MatchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching.v1.MatchingService",
	HandlerType: (*MatchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignMentor",
			Handler:    _MatchingService_AssignMentor_Handler,
		},
		{
			MethodName: "SkipQuestion",
			Handler:    _MatchingService_SkipQuestion_Handler,
		},
		{
			MethodName: "GetNextQuestion",
			Handler:    _MatchingService_GetNextQuestion_Handler,
		},
		{
			MethodName: "GetPendingForMentor",
			Handler:    _MatchingService_GetPendingForMentor_Handler,
		},
		{
			MethodName: "EscalateQuestion",
			Handler:    _MatchingService_EscalateQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching/v1/matching.proto",
}
