// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: matching/v1/matching.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignmentStatus int32

const (
	AssignmentStatus_ASSIGNMENT_STATUS_UNSPECIFIED AssignmentStatus = 0
	AssignmentStatus_ASSIGNMENT_STATUS_PENDING     AssignmentStatus = 1
	AssignmentStatus_ASSIGNMENT_STATUS_SKIPPED     AssignmentStatus = 2
	AssignmentStatus_ASSIGNMENT_STATUS_IN_PROGRESS AssignmentStatus = 3
	AssignmentStatus_ASSIGNMENT_STATUS_COMPLETED   AssignmentStatus = 4
)

// Enum value maps for AssignmentStatus.
var (
	AssignmentStatus_name = map[int32]string{
		0: "ASSIGNMENT_STATUS_UNSPECIFIED",
		1: "ASSIGNMENT_STATUS_PENDING",
		2: "ASSIGNMENT_STATUS_SKIPPED",
		3: "ASSIGNMENT_STATUS_IN_PROGRESS",
		4: "ASSIGNMENT_STATUS_COMPLETED",
	}
	AssignmentStatus_value = map[string]int32{
		"ASSIGNMENT_STATUS_UNSPECIFIED": 0,
		"ASSIGNMENT_STATUS_PENDING":     1,
		"ASSIGNMENT_STATUS_SKIPPED":     2,
		"ASSIGNMENT_STATUS_IN_PROGRESS": 3,
		"ASSIGNMENT_STATUS_COMPLETED":   4,
	}
)

func (x AssignmentStatus) Enum() *AssignmentStatus {
	p := new(AssignmentStatus)
	*p = x
	return p
}

func (x AssignmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_v1_matching_proto_enumTypes[0].Descriptor()
}

func (AssignmentStatus) Type() protoreflect.EnumType {
	return &file_matching_v1_matching_proto_enumTypes[0]
}

func (x AssignmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignmentStatus.Descriptor instead.
func (AssignmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{0}
}

type Urgency int32

const (
	Urgency_URGENCY_UNSPECIFIED Urgency = 0
	Urgency_URGENCY_LOW         Urgency = 1
	Urgency_URGENCY_NORMAL      Urgency = 2
	Urgency_URGENCY_URGENT      Urgency = 3
)

// Enum value maps for Urgency.
var (
	Urgency_name = map[int32]string{
		0: "URGENCY_UNSPECIFIED",
		1: "URGENCY_LOW",
		2: "URGENCY_NORMAL",
		3: "URGENCY_URGENT",
	}
	Urgency_value = map[string]int32{
		"URGENCY_UNSPECIFIED": 0,
		"URGENCY_LOW":         1,
		"URGENCY_NORMAL":      2,
		"URGENCY_URGENT":      3,
	}
)

func (x Urgency) Enum() *Urgency {
	p := new(Urgency)
	*p = x
	return p
}

func (x Urgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Urgency) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_v1_matching_proto_enumTypes[1].Descriptor()
}

func (Urgency) Type() protoreflect.EnumType {
	return &file_matching_v1_matching_proto_enumTypes[1]
}

func (x Urgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Urgency.Descriptor instead.
func (Urgency) EnumDescriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{1}
}

type AssignMentorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Urgency       Urgency                `protobuf:"varint,3,opt,name=urgency,proto3,enum=matching.v1.Urgency" json:"urgency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMentorRequest) Reset() {
	*x = AssignMentorRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMentorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMentorRequest) ProtoMessage() {}

func (x *AssignMentorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMentorRequest.ProtoReflect.Descriptor instead.
func (*AssignMentorRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{0}
}

func (x *AssignMentorRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AssignMentorRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AssignMentorRequest) GetUrgency() Urgency {
	if x != nil {
		return x.Urgency
	}
	return Urgency_URGENCY_UNSPECIFIED
}

type AssignMentorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	MentorId      string                 `protobuf:"bytes,2,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	Status        AssignmentStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=matching.v1.AssignmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMentorResponse) Reset() {
	*x = AssignMentorResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMentorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMentorResponse) ProtoMessage() {}

func (x *AssignMentorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMentorResponse.ProtoReflect.Descriptor instead.
func (*AssignMentorResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{1}
}

func (x *AssignMentorResponse) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *AssignMentorResponse) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *AssignMentorResponse) GetStatus() AssignmentStatus {
	if x != nil {
		return x.Status
	}
	return AssignmentStatus_ASSIGNMENT_STATUS_UNSPECIFIED
}

type SkipQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	MentorId      string                 `protobuf:"bytes,2,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipQuestionRequest) Reset() {
	*x = SkipQuestionRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipQuestionRequest) ProtoMessage() {}

func (x *SkipQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipQuestionRequest.ProtoReflect.Descriptor instead.
func (*SkipQuestionRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{2}
}

func (x *SkipQuestionRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *SkipQuestionRequest) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *SkipQuestionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SkipQuestionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Skipped          bool                   `protobuf:"varint,1,opt,name=skipped,proto3" json:"skipped,omitempty"`
	NeedReassignment bool                   `protobuf:"varint,2,opt,name=need_reassignment,json=needReassignment,proto3" json:"need_reassignment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SkipQuestionResponse) Reset() {
	*x = SkipQuestionResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipQuestionResponse) ProtoMessage() {}

func (x *SkipQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipQuestionResponse.ProtoReflect.Descriptor instead.
func (*SkipQuestionResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{3}
}

func (x *SkipQuestionResponse) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

func (x *SkipQuestionResponse) GetNeedReassignment() bool {
	if x != nil {
		return x.NeedReassignment
	}
	return false
}

type GetNextQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentorId      string                 `protobuf:"bytes,1,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextQuestionRequest) Reset() {
	*x = GetNextQuestionRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextQuestionRequest) ProtoMessage() {}

func (x *GetNextQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetNextQuestionRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{4}
}

func (x *GetNextQuestionRequest) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

type GetNextQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,6,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextQuestionResponse) Reset() {
	*x = GetNextQuestionResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextQuestionResponse) ProtoMessage() {}

func (x *GetNextQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetNextQuestionResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{5}
}

func (x *GetNextQuestionResponse) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *GetNextQuestionResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetNextQuestionResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetNextQuestionResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetNextQuestionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetNextQuestionResponse) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type GetPendingForMentorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentorId      string                 `protobuf:"bytes,1,opt,name=mentor_id,json=mentorId,proto3" json:"mentor_id,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingForMentorRequest) Reset() {
	*x = GetPendingForMentorRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingForMentorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingForMentorRequest) ProtoMessage() {}

func (x *GetPendingForMentorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingForMentorRequest.ProtoReflect.Descriptor instead.
func (*GetPendingForMentorRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{6}
}

func (x *GetPendingForMentorRequest) GetMentorId() string {
	if x != nil {
		return x.MentorId
	}
	return ""
}

func (x *GetPendingForMentorRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetPendingForMentorRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPendingForMentorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*PendingQuestion     `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingForMentorResponse) Reset() {
	*x = GetPendingForMentorResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingForMentorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingForMentorResponse) ProtoMessage() {}

func (x *GetPendingForMentorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingForMentorResponse.ProtoReflect.Descriptor instead.
func (*GetPendingForMentorResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingForMentorResponse) GetQuestions() []*PendingQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetPendingForMentorResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PendingQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Urgency       Urgency                `protobuf:"varint,5,opt,name=urgency,proto3,enum=matching.v1.Urgency" json:"urgency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingQuestion) Reset() {
	*x = PendingQuestion{}
	mi := &file_matching_v1_matching_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingQuestion) ProtoMessage() {}

func (x *PendingQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingQuestion.ProtoReflect.Descriptor instead.
func (*PendingQuestion) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{8}
}

func (x *PendingQuestion) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *PendingQuestion) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PendingQuestion) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PendingQuestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PendingQuestion) GetUrgency() Urgency {
	if x != nil {
		return x.Urgency
	}
	return Urgency_URGENCY_UNSPECIFIED
}

func (x *PendingQuestion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type EscalateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscalateQuestionRequest) Reset() {
	*x = EscalateQuestionRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalateQuestionRequest) ProtoMessage() {}

func (x *EscalateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalateQuestionRequest.ProtoReflect.Descriptor instead.
func (*EscalateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{9}
}

func (x *EscalateQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *EscalateQuestionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EscalateQuestionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EscalationLevel int32                  `protobuf:"varint,1,opt,name=escalation_level,json=escalationLevel,proto3" json:"escalation_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EscalateQuestionResponse) Reset() {
	*x = EscalateQuestionResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalateQuestionResponse) ProtoMessage() {}

func (x *EscalateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalateQuestionResponse.ProtoReflect.Descriptor instead.
func (*EscalateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{10}
}

func (x *EscalateQuestionResponse) GetEscalationLevel() int32 {
	if x != nil {
		return x.EscalationLevel
	}
	return 0
}

var File_matching_v1_matching_proto protoreflect.FileDescriptor

const file_matching_v1_matching_proto_rawDesc = "" +
	"\n" +
	"\x1amatching/v1/matching.proto\x12\vmatching.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x13AssignMentorRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12.\n" +
	"\aurgency\x18\x03 \x01(\x0e2\x14.matching.v1.UrgencyR\aurgency\"\x8f\x01\n" +
	"\x14AssignMentorResponse\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tmentor_id\x18\x02 \x01(\tR\bmentorId\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.matching.v1.AssignmentStatusR\x06status\"o\n" +
	"\x13SkipQuestionRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tmentor_id\x18\x02 \x01(\tR\bmentorId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"]\n" +
	"\x14SkipQuestionResponse\x12\x18\n" +
	"\askipped\x18\x01 \x01(\bR\askipped\x12+\n" +
	"\x11need_reassignment\x18\x02 \x01(\bR\x10needReassignment\"5\n" +
	"\x16GetNextQuestionRequest\x12\x1b\n" +
	"\tmentor_id\x18\x01 \x01(\tR\bmentorId\"\xca\x01\n" +
	"\x17GetNextQuestionResponse\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x06 \x03(\tR\timageUrls\"u\n" +
	"\x1aGetPendingForMentorRequest\x12\x1b\n" +
	"\tmentor_id\x18\x01 \x01(\tR\bmentorId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\x1bGetPendingForMentorResponse\x12:\n" +
	"\tquestions\x18\x01 \x03(\v2\x1c.matching.v1.PendingQuestionR\tquestions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xef\x01\n" +
	"\x0fPendingQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12.\n" +
	"\aurgency\x18\x05 \x01(\x0e2\x14.matching.v1.UrgencyR\aurgency\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x17EscalateQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"E\n" +
	"\x18EscalateQuestionResponse\x12)\n" +
	"\x10escalation_level\x18\x01 \x01(\x05R\x0fescalationLevel*\xb7\x01\n" +
	"\x10AssignmentStatus\x12!\n" +
	"\x1dASSIGNMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ASSIGNMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19ASSIGNMENT_STATUS_SKIPPED\x10\x02\x12!\n" +
	"\x1dASSIGNMENT_STATUS_IN_PROGRESS\x10\x03\x12\x1f\n" +
	"\x1bASSIGNMENT_STATUS_COMPLETED\x10\x04*[\n" +
	"\aUrgency\x12\x17\n" +
	"\x13URGENCY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vURGENCY_LOW\x10\x01\x12\x12\n" +
	"\x0eURGENCY_NORMAL\x10\x02\x12\x12\n" +
	"\x0eURGENCY_URGENT\x10\x032\xe4\x03\n" +
	"\x0fMatchingService\x12S\n" +
	"\fAssignMentor\x12 .matching.v1.AssignMentorRequest\x1a!.matching.v1.AssignMentorResponse\x12S\n" +
	"\fSkipQuestion\x12 .matching.v1.SkipQuestionRequest\x1a!.matching.v1.SkipQuestionResponse\x12\\\n" +
	"\x0fGetNextQuestion\x12#.matching.v1.GetNextQuestionRequest\x1a$.matching.v1.GetNextQuestionResponse\x12h\n" +
	"\x13GetPendingForMentor\x12'.matching.v1.GetPendingForMentorRequest\x1a(.matching.v1.GetPendingForMentorResponse\x12_\n" +
	"\x10EscalateQuestion\x12$.matching.v1.EscalateQuestionRequest\x1a%.matching.v1.EscalateQuestionResponseB!Z\x1fpreppi.com/proto/matching/v1;v1b\x06proto3"

var (
	file_matching_v1_matching_proto_rawDescOnce sync.Once
	file_matching_v1_matching_proto_rawDescData []byte
)

func file_matching_v1_matching_proto_rawDescGZIP() []byte {
	file_matching_v1_matching_proto_rawDescOnce.Do(func() {
		file_matching_v1_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_matching_proto_rawDesc), len(file_matching_v1_matching_proto_rawDesc)))
	})
	return file_matching_v1_matching_proto_rawDescData
}

var file_matching_v1_matching_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_matching_v1_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_matching_v1_matching_proto_goTypes = []any{
	(AssignmentStatus)(0),               // 0: matching.v1.AssignmentStatus
	(Urgency)(0),                        // 1: matching.v1.Urgency
	(*AssignMentorRequest)(nil),         // 2: matching.v1.AssignMentorRequest
	(*AssignMentorResponse)(nil),        // 3: matching.v1.AssignMentorResponse
	(*SkipQuestionRequest)(nil),         // 4: matching.v1.SkipQuestionRequest
	(*SkipQuestionResponse)(nil),        // 5: matching.v1.SkipQuestionResponse
	(*GetNextQuestionRequest)(nil),      // 6: matching.v1.GetNextQuestionRequest
	(*GetNextQuestionResponse)(nil),     // 7: matching.v1.GetNextQuestionResponse
	(*GetPendingForMentorRequest)(nil),  // 8: matching.v1.GetPendingForMentorRequest
	(*GetPendingForMentorResponse)(nil), // 9: matching.v1.GetPendingForMentorResponse
	(*PendingQuestion)(nil),             // 10: matching.v1.PendingQuestion
	(*EscalateQuestionRequest)(nil),     // 11: matching.v1.EscalateQuestionRequest
	(*EscalateQuestionResponse)(nil),    // 12: matching.v1.EscalateQuestionResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_matching_v1_matching_proto_depIdxs = []int32{
	1,  // 0: matching.v1.AssignMentorRequest.urgency:type_name -> matching.v1.Urgency
	0,  // 1: matching.v1.AssignMentorResponse.status:type_name -> matching.v1.AssignmentStatus
	10, // 2: matching.v1.GetPendingForMentorResponse.questions:type_name -> matching.v1.PendingQuestion
	1,  // 3: matching.v1.PendingQuestion.urgency:type_name -> matching.v1.Urgency
	13, // 4: matching.v1.PendingQuestion.created_at:type_name -> google.protobuf.Timestamp
	2,  // 5: matching.v1.MatchingService.AssignMentor:input_type -> matching.v1.AssignMentorRequest
	4,  // 6: matching.v1.MatchingService.SkipQuestion:input_type -> matching.v1.SkipQuestionRequest
	6,  // 7: matching.v1.MatchingService.GetNextQuestion:input_type -> matching.v1.GetNextQuestionRequest
	8,  // 8: matching.v1.MatchingService.GetPendingForMentor:input_type -> matching.v1.GetPendingForMentorRequest
	11, // 9: matching.v1.MatchingService.EscalateQuestion:input_type -> matching.v1.EscalateQuestionRequest
	3,  // 10: matching.v1.MatchingService.AssignMentor:output_type -> matching.v1.AssignMentorResponse
	5,  // 11: matching.v1.MatchingService.SkipQuestion:output_type -> matching.v1.SkipQuestionResponse
	7,  // 12: matching.v1.MatchingService.GetNextQuestion:output_type -> matching.v1.GetNextQuestionResponse
	9,  // 13: matching.v1.MatchingService.GetPendingForMentor:output_type -> matching.v1.GetPendingForMentorResponse
	12, // 14: matching.v1.MatchingService.EscalateQuestion:output_type -> matching.v1.EscalateQuestionResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_matching_v1_matching_proto_init() }
func file_matching_v1_matching_proto_init() {
	if File_matching_v1_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_matching_proto_rawDesc), len(file_matching_v1_matching_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_v1_matching_proto_goTypes,
		DependencyIndexes: file_matching_v1_matching_proto_depIdxs,
		EnumInfos:         file_matching_v1_matching_proto_enumTypes,
		MessageInfos:      file_matching_v1_matching_proto_msgTypes,
	}.Build()
	File_matching_v1_matching_proto = out.File
	file_matching_v1_matching_proto_goTypes = nil
	file_matching_v1_matching_proto_depIdxs = nil
}
