// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: user/v1/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationStatus int32

const (
	VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED VerificationStatus = 0
	VerificationStatus_VERIFICATION_STATUS_PENDING     VerificationStatus = 1
	VerificationStatus_VERIFICATION_STATUS_APPROVED    VerificationStatus = 2
	VerificationStatus_VERIFICATION_STATUS_REJECTED    VerificationStatus = 3
)

// Enum value maps for VerificationStatus.
var (
	VerificationStatus_name = map[int32]string{
		0: "VERIFICATION_STATUS_UNSPECIFIED",
		1: "VERIFICATION_STATUS_PENDING",
		2: "VERIFICATION_STATUS_APPROVED",
		3: "VERIFICATION_STATUS_REJECTED",
	}
	VerificationStatus_value = map[string]int32{
		"VERIFICATION_STATUS_UNSPECIFIED": 0,
		"VERIFICATION_STATUS_PENDING":     1,
		"VERIFICATION_STATUS_APPROVED":    2,
		"VERIFICATION_STATUS_REJECTED":    3,
	}
)

func (x VerificationStatus) Enum() *VerificationStatus {
	p := new(VerificationStatus)
	*p = x
	return p
}

func (x VerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (VerificationStatus) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x VerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationStatus.Descriptor instead.
func (VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

type OnlineStatus int32

const (
	OnlineStatus_ONLINE_STATUS_UNSPECIFIED OnlineStatus = 0
	OnlineStatus_ONLINE_STATUS_ONLINE      OnlineStatus = 1
	OnlineStatus_ONLINE_STATUS_OFFLINE     OnlineStatus = 2
)

// Enum value maps for OnlineStatus.
var (
	OnlineStatus_name = map[int32]string{
		0: "ONLINE_STATUS_UNSPECIFIED",
		1: "ONLINE_STATUS_ONLINE",
		2: "ONLINE_STATUS_OFFLINE",
	}
	OnlineStatus_value = map[string]int32{
		"ONLINE_STATUS_UNSPECIFIED": 0,
		"ONLINE_STATUS_ONLINE":      1,
		"ONLINE_STATUS_OFFLINE":     2,
	}
)

func (x OnlineStatus) Enum() *OnlineStatus {
	p := new(OnlineStatus)
	*p = x
	return p
}

func (x OnlineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnlineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[1].Descriptor()
}

func (OnlineStatus) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[1]
}

func (x OnlineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnlineStatus.Descriptor instead.
func (OnlineStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_STUDENT     Role = 1
	Role_ROLE_MENTOR      Role = 2
	Role_ROLE_ADMIN       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_STUDENT",
		2: "ROLE_MENTOR",
		3: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_STUDENT":     1,
		"ROLE_MENTOR":      2,
		"ROLE_ADMIN":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

type CreateProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl         string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Phone             string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	School            string                 `protobuf:"bytes,5,opt,name=school,proto3" json:"school,omitempty"`
	College           string                 `protobuf:"bytes,6,opt,name=college,proto3" json:"college,omitempty"`
	Bio               string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Role              Role                   `protobuf:"varint,8,opt,name=role,proto3,enum=user.v1.Role" json:"role,omitempty"`
	ExpertiseSubjects []string               `protobuf:"bytes,9,rep,name=expertise_subjects,json=expertiseSubjects,proto3" json:"expertise_subjects,omitempty"`
	SubTopics         []string               `protobuf:"bytes,10,rep,name=sub_topics,json=subTopics,proto3" json:"sub_topics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CreateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateProfileRequest) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *CreateProfileRequest) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *CreateProfileRequest) GetExpertiseSubjects() []string {
	if x != nil {
		return x.ExpertiseSubjects
	}
	return nil
}

func (x *CreateProfileRequest) GetSubTopics() []string {
	if x != nil {
		return x.SubTopics
	}
	return nil
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	School        string                 `protobuf:"bytes,6,opt,name=school,proto3" json:"school,omitempty"`
	College       string                 `protobuf:"bytes,7,opt,name=college,proto3" json:"college,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *UpdateProfileRequest) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateMentorProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpertiseSubjects []string               `protobuf:"bytes,2,rep,name=expertise_subjects,json=expertiseSubjects,proto3" json:"expertise_subjects,omitempty"`
	SubTopics         []string               `protobuf:"bytes,3,rep,name=sub_topics,json=subTopics,proto3" json:"sub_topics,omitempty"`
	Bio               string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateMentorProfileRequest) Reset() {
	*x = UpdateMentorProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMentorProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMentorProfileRequest) ProtoMessage() {}

func (x *UpdateMentorProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMentorProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMentorProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMentorProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMentorProfileRequest) GetExpertiseSubjects() []string {
	if x != nil {
		return x.ExpertiseSubjects
	}
	return nil
}

func (x *UpdateMentorProfileRequest) GetSubTopics() []string {
	if x != nil {
		return x.SubTopics
	}
	return nil
}

func (x *UpdateMentorProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateMentorProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mentor        *MentorProfile         `protobuf:"bytes,1,opt,name=mentor,proto3" json:"mentor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMentorProfileResponse) Reset() {
	*x = UpdateMentorProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMentorProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMentorProfileResponse) ProtoMessage() {}

func (x *UpdateMentorProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMentorProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateMentorProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMentorProfileResponse) GetMentor() *MentorProfile {
	if x != nil {
		return x.Mentor
	}
	return nil
}

type GetMentorsBySubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMentorsBySubjectRequest) Reset() {
	*x = GetMentorsBySubjectRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMentorsBySubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMentorsBySubjectRequest) ProtoMessage() {}

func (x *GetMentorsBySubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMentorsBySubjectRequest.ProtoReflect.Descriptor instead.
func (*GetMentorsBySubjectRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetMentorsBySubjectRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetMentorsBySubjectRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMentorsBySubjectRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetMentorsBySubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mentors       []*MentorProfile       `protobuf:"bytes,1,rep,name=mentors,proto3" json:"mentors,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMentorsBySubjectResponse) Reset() {
	*x = GetMentorsBySubjectResponse{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMentorsBySubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMentorsBySubjectResponse) ProtoMessage() {}

func (x *GetMentorsBySubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMentorsBySubjectResponse.ProtoReflect.Descriptor instead.
func (*GetMentorsBySubjectResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetMentorsBySubjectResponse) GetMentors() []*MentorProfile {
	if x != nil {
		return x.Mentors
	}
	return nil
}

func (x *GetMentorsBySubjectResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SetOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OnlineStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=user.v1.OnlineStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOnlineStatusRequest) Reset() {
	*x = SetOnlineStatusRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineStatusRequest) ProtoMessage() {}

func (x *SetOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*SetOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *SetOnlineStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetOnlineStatusRequest) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

type SetOnlineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOnlineStatusResponse) Reset() {
	*x = SetOnlineStatusResponse{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineStatusResponse) ProtoMessage() {}

func (x *SetOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*SetOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *SetOnlineStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApproveMentorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveMentorRequest) Reset() {
	*x = ApproveMentorRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveMentorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveMentorRequest) ProtoMessage() {}

func (x *ApproveMentorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveMentorRequest.ProtoReflect.Descriptor instead.
func (*ApproveMentorRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveMentorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApproveMentorRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ApproveMentorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        VerificationStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=user.v1.VerificationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveMentorResponse) Reset() {
	*x = ApproveMentorResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveMentorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveMentorResponse) ProtoMessage() {}

func (x *ApproveMentorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveMentorResponse.ProtoReflect.Descriptor instead.
func (*ApproveMentorResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveMentorResponse) GetStatus() VerificationStatus {
	if x != nil {
		return x.Status
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	School        string                 `protobuf:"bytes,5,opt,name=school,proto3" json:"school,omitempty"`
	College       string                 `protobuf:"bytes,6,opt,name=college,proto3" json:"college,omitempty"`
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Role          Role                   `protobuf:"varint,8,opt,name=role,proto3,enum=user.v1.Role" json:"role,omitempty"`
	OnlineStatus  OnlineStatus           `protobuf:"varint,9,opt,name=online_status,json=onlineStatus,proto3,enum=user.v1.OnlineStatus" json:"online_status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *Profile) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Profile) GetOnlineStatus() OnlineStatus {
	if x != nil {
		return x.OnlineStatus
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MentorProfile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl          string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ExpertiseSubjects  []string               `protobuf:"bytes,4,rep,name=expertise_subjects,json=expertiseSubjects,proto3" json:"expertise_subjects,omitempty"`
	SubTopics          []string               `protobuf:"bytes,5,rep,name=sub_topics,json=subTopics,proto3" json:"sub_topics,omitempty"`
	VerificationStatus VerificationStatus     `protobuf:"varint,6,opt,name=verification_status,json=verificationStatus,proto3,enum=user.v1.VerificationStatus" json:"verification_status,omitempty"`
	Rating             float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	QuestionsAnswered  int32                  `protobuf:"varint,8,opt,name=questions_answered,json=questionsAnswered,proto3" json:"questions_answered,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MentorProfile) Reset() {
	*x = MentorProfile{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorProfile) ProtoMessage() {}

func (x *MentorProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorProfile.ProtoReflect.Descriptor instead.
func (*MentorProfile) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *MentorProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MentorProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MentorProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *MentorProfile) GetExpertiseSubjects() []string {
	if x != nil {
		return x.ExpertiseSubjects
	}
	return nil
}

func (x *MentorProfile) GetSubTopics() []string {
	if x != nil {
		return x.SubTopics
	}
	return nil
}

func (x *MentorProfile) GetVerificationStatus() VerificationStatus {
	if x != nil {
		return x.VerificationStatus
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *MentorProfile) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MentorProfile) GetQuestionsAnswered() int32 {
	if x != nil {
		return x.QuestionsAnswered
	}
	return 0
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xad\x02\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06school\x18\x05 \x01(\tR\x06school\x12\x18\n" +
	"\acollege\x18\x06 \x01(\tR\acollege\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12!\n" +
	"\x04role\x18\b \x01(\x0e2\r.user.v1.RoleR\x04role\x12-\n" +
	"\x12expertise_subjects\x18\t \x03(\tR\x11expertiseSubjects\x12\x1d\n" +
	"\n" +
	"sub_topics\x18\n" +
	" \x03(\tR\tsubTopics\"C\n" +
	"\x15CreateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.user.v1.ProfileR\aprofile\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x12GetProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.user.v1.ProfileR\aprofile\"\xe3\x01\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x16\n" +
	"\x06school\x18\x06 \x01(\tR\x06school\x12\x18\n" +
	"\acollege\x18\a \x01(\tR\acollege\"C\n" +
	"\x15UpdateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.user.v1.ProfileR\aprofile\"\x95\x01\n" +
	"\x1aUpdateMentorProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x12expertise_subjects\x18\x02 \x03(\tR\x11expertiseSubjects\x12\x1d\n" +
	"\n" +
	"sub_topics\x18\x03 \x03(\tR\tsubTopics\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\"M\n" +
	"\x1bUpdateMentorProfileResponse\x12.\n" +
	"\x06mentor\x18\x01 \x01(\v2\x16.user.v1.MentorProfileR\x06mentor\"r\n" +
	"\x1aGetMentorsBySubjectRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"w\n" +
	"\x1bGetMentorsBySubjectResponse\x120\n" +
	"\amentors\x18\x01 \x03(\v2\x16.user.v1.MentorProfileR\amentors\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"`\n" +
	"\x16SetOnlineStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.user.v1.OnlineStatusR\x06status\"3\n" +
	"\x17SetOnlineStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x14ApproveMentorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"L\n" +
	"\x15ApproveMentorResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.user.v1.VerificationStatusR\x06status\"\xc9\x02\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06school\x18\x05 \x01(\tR\x06school\x12\x18\n" +
	"\acollege\x18\x06 \x01(\tR\acollege\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12!\n" +
	"\x04role\x18\b \x01(\x0e2\r.user.v1.RoleR\x04role\x12:\n" +
	"\ronline_status\x18\t \x01(\x0e2\x15.user.v1.OnlineStatusR\fonlineStatus\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbe\x02\n" +
	"\rMentorProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12-\n" +
	"\x12expertise_subjects\x18\x04 \x03(\tR\x11expertiseSubjects\x12\x1d\n" +
	"\n" +
	"sub_topics\x18\x05 \x03(\tR\tsubTopics\x12L\n" +
	"\x13verification_status\x18\x06 \x01(\x0e2\x1b.user.v1.VerificationStatusR\x12verificationStatus\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12-\n" +
	"\x12questions_answered\x18\b \x01(\x05R\x11questionsAnswered*\x9e\x01\n" +
	"\x12VerificationStatus\x12#\n" +
	"\x1fVERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVERIFICATION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cVERIFICATION_STATUS_APPROVED\x10\x02\x12 \n" +
	"\x1cVERIFICATION_STATUS_REJECTED\x10\x03*b\n" +
	"\fOnlineStatus\x12\x1d\n" +
	"\x19ONLINE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ONLINE_STATUS_ONLINE\x10\x01\x12\x19\n" +
	"\x15ONLINE_STATUS_OFFLINE\x10\x02*O\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fROLE_STUDENT\x10\x01\x12\x0f\n" +
	"\vROLE_MENTOR\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x032\xde\x04\n" +
	"\vUserService\x12N\n" +
	"\rCreateProfile\x12\x1d.user.v1.CreateProfileRequest\x1a\x1e.user.v1.CreateProfileResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.user.v1.GetProfileRequest\x1a\x1b.user.v1.GetProfileResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.user.v1.UpdateProfileRequest\x1a\x1e.user.v1.UpdateProfileResponse\x12`\n" +
	"\x13UpdateMentorProfile\x12#.user.v1.UpdateMentorProfileRequest\x1a$.user.v1.UpdateMentorProfileResponse\x12`\n" +
	"\x13GetMentorsBySubject\x12#.user.v1.GetMentorsBySubjectRequest\x1a$.user.v1.GetMentorsBySubjectResponse\x12T\n" +
	"\x0fSetOnlineStatus\x12\x1f.user.v1.SetOnlineStatusRequest\x1a .user.v1.SetOnlineStatusResponse\x12N\n" +
	"\rApproveMentor\x12\x1d.user.v1.ApproveMentorRequest\x1a\x1e.user.v1.ApproveMentorResponseB\x1dZ\x1bpreppi.com/proto/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_v1_user_proto_goTypes = []any{
	(VerificationStatus)(0),             // 0: user.v1.VerificationStatus
	(OnlineStatus)(0),                   // 1: user.v1.OnlineStatus
	(Role)(0),                           // 2: user.v1.Role
	(*CreateProfileRequest)(nil),        // 3: user.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),       // 4: user.v1.CreateProfileResponse
	(*GetProfileRequest)(nil),           // 5: user.v1.GetProfileRequest
	(*GetProfileResponse)(nil),          // 6: user.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),        // 7: user.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 8: user.v1.UpdateProfileResponse
	(*UpdateMentorProfileRequest)(nil),  // 9: user.v1.UpdateMentorProfileRequest
	(*UpdateMentorProfileResponse)(nil), // 10: user.v1.UpdateMentorProfileResponse
	(*GetMentorsBySubjectRequest)(nil),  // 11: user.v1.GetMentorsBySubjectRequest
	(*GetMentorsBySubjectResponse)(nil), // 12: user.v1.GetMentorsBySubjectResponse
	(*SetOnlineStatusRequest)(nil),      // 13: user.v1.SetOnlineStatusRequest
	(*SetOnlineStatusResponse)(nil),     // 14: user.v1.SetOnlineStatusResponse
	(*ApproveMentorRequest)(nil),        // 15: user.v1.ApproveMentorRequest
	(*ApproveMentorResponse)(nil),       // 16: user.v1.ApproveMentorResponse
	(*Profile)(nil),                     // 17: user.v1.Profile
	(*MentorProfile)(nil),               // 18: user.v1.MentorProfile
	(*fieldmaskpb.FieldMask)(nil),       // 19: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil),       // 20: google.protobuf.Timestamp
}
var file_user_v1_user_proto_depIdxs = []int32{
	2,  // 0: user.v1.CreateProfileRequest.role:type_name -> user.v1.Role
	17, // 1: user.v1.CreateProfileResponse.profile:type_name -> user.v1.Profile
	17, // 2: user.v1.GetProfileResponse.profile:type_name -> user.v1.Profile
	19, // 3: user.v1.UpdateProfileRequest.update_mask:type_name -> google.protobuf.FieldMask
	17, // 4: user.v1.UpdateProfileResponse.profile:type_name -> user.v1.Profile
	18, // 5: user.v1.UpdateMentorProfileResponse.mentor:type_name -> user.v1.MentorProfile
	18, // 6: user.v1.GetMentorsBySubjectResponse.mentors:type_name -> user.v1.MentorProfile
	1,  // 7: user.v1.SetOnlineStatusRequest.status:type_name -> user.v1.OnlineStatus
	0,  // 8: user.v1.ApproveMentorResponse.status:type_name -> user.v1.VerificationStatus
	2,  // 9: user.v1.Profile.role:type_name -> user.v1.Role
	1,  // 10: user.v1.Profile.online_status:type_name -> user.v1.OnlineStatus
	20, // 11: user.v1.Profile.created_at:type_name -> google.protobuf.Timestamp
	0,  // 12: user.v1.MentorProfile.verification_status:type_name -> user.v1.VerificationStatus
	3,  // 13: user.v1.UserService.CreateProfile:input_type -> user.v1.CreateProfileRequest
	5,  // 14: user.v1.UserService.GetProfile:input_type -> user.v1.GetProfileRequest
	7,  // 15: user.v1.UserService.UpdateProfile:input_type -> user.v1.UpdateProfileRequest
	9,  // 16: user.v1.UserService.UpdateMentorProfile:input_type -> user.v1.UpdateMentorProfileRequest
	11, // 17: user.v1.UserService.GetMentorsBySubject:input_type -> user.v1.GetMentorsBySubjectRequest
	13, // 18: user.v1.UserService.SetOnlineStatus:input_type -> user.v1.SetOnlineStatusRequest
	15, // 19: user.v1.UserService.ApproveMentor:input_type -> user.v1.ApproveMentorRequest
	4,  // 20: user.v1.UserService.CreateProfile:output_type -> user.v1.CreateProfileResponse
	6,  // 21: user.v1.UserService.GetProfile:output_type -> user.v1.GetProfileResponse
	8,  // 22: user.v1.UserService.UpdateProfile:output_type -> user.v1.UpdateProfileResponse
	10, // 23: user.v1.UserService.UpdateMentorProfile:output_type -> user.v1.UpdateMentorProfileResponse
	12, // 24: user.v1.UserService.GetMentorsBySubject:output_type -> user.v1.GetMentorsBySubjectResponse
	14, // 25: user.v1.UserService.SetOnlineStatus:output_type -> user.v1.SetOnlineStatusResponse
	16, // 26: user.v1.UserService.ApproveMentor:output_type -> user.v1.ApproveMentorResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
